import type { LandingCopy } from './ar'

/**
 * النصوص الإنجليزية. النوع LandingCopy يفرض تطابق المفاتيح مع العربية،
 * فأي مفتاح ناقص أو زائد يوقف البناء.
 * لا حاجة لعزل الاتجاه هنا لأن السياق LTR أصلًا.
 */
export const en: LandingCopy = {
  meta: {
    title: 'Majarra | A whole world of stories and knowledge for your child',
    description: 'A safe Arabic-first platform for ages 3 to 12: series, picture books, audio stories, games and learning content.',
  },

  common: {
    skip: 'Skip to content',
    brandLabel: 'Majarra, home page',
    langAria: 'Choose language',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    login: 'Sign in',
    startFree: 'Start free',
    details: 'Details',
  },

  nav: {
    home: 'Home',
    discover: 'Discover',
    worlds: 'Planets',
    parents: 'For parents',
    plans: 'Plans',
    devices: 'Devices',
    partners: 'Partnerships',
    discoverAria: 'Discover menu',
    mainAria: 'Main navigation',
  },

  mega: {
    watch: { title: 'Watch', links: ['Series', 'Films', 'Short episodes', 'Learning content'] },
    read: { title: 'Read', links: ['Picture books', 'Comics', 'Books', 'Planet of Stories'] },
    listen: { title: 'Listen', links: ['Audio stories', 'Bedtime', 'Songs'] },
    play: { title: 'Play', links: ['Learning games', 'Challenges', 'Activities'] },
    learn: { title: 'Learn', links: ['Language', 'Science', 'Numbers', 'History', 'Skills'] },
  },

  hero: {
    eyebrow: 'A safe Arabic-first platform for children aged 3 to 12',
    slides: [
      {
        title: 'A whole world of stories',
        accent: 'and knowledge for your child',
        copy: 'Watch series, read stories, listen to tales, and play safe learning games in Arabic and other languages.',
      },
      {
        title: 'A story your child reads…',
        accent: 'or one that reads itself',
        copy: 'Picture books and comics with four reading modes, narration for every page, sentence highlighting while reading, and offline downloads.',
      },
      {
        title: 'Your child explores freely…',
        accent: 'and you stay in control',
        copy: 'A separate profile per child, age-appropriate content, a parent PIN, screen-time limits, and a clear weekly report on reading and learning.',
      },
    ],
    notes: ['Safe for children', 'No ads on the Family plan', 'Works on all your devices'],
    ctaPrimary: 'Start your free trial',
    ctaSecondary: 'Explore Majarra content',
    dotsAria: 'Slides',
    slideAria: (index: number, title: string) => `Slide ${index}: ${title}`,
    tvAlt: 'A scene from Explorers’ Adventures shown on a television screen',
    tabletAlt: 'A picture book shown on a tablet',
    phoneAlt: 'Luna Discovers Words series poster on a phone',
    floatA: { title: 'Start on the tablet', text: 'and continue on the TV from the same page' },
    floatB: { title: 'A weekly parent report', text: 'reading and skill progress, clearly' },
  },

  trust: [
    'Suitable for ages 3–12',
    'Arabic and international content',
    'Multiple child profiles',
    'Download for offline viewing',
    'Phone, tablet and TV',
    'Parental controls and reports',
  ],

  pillars: {
    kicker: 'Five pillars, one platform',
    heading: 'Everything your child loves',
    accent: 'in one place',
    copy: 'Majarra is not just a video library. Watching, reading, listening, playing and learning are connected in a single experience, each designed for the child’s age.',
    items: {
      watch: {
        title: 'Watch',
        copy: 'Series, films, short episodes and learning content matched to your child’s age, in high quality with clear seasons and episodes.',
        link: 'Browse series',
      },
      read: {
        title: 'Read',
        copy: 'Multilingual picture books and comics, read independently or with the narrator, with sentence highlighting while reading.',
        link: 'Browse stories',
      },
      listen: {
        title: 'Listen',
        copy: 'Audio stories, bedtime tales and songs with calm voices and effects, at a volume and tone suited to sleep.',
        link: 'Browse audio',
      },
      play: {
        title: 'Play',
        copy: 'Games and challenges that tie fun to skills and learning, with no pressure timers and no rewards tied to screen time.',
        link: 'Browse games',
      },
      learn: {
        title: 'Learn',
        copy: 'Content organised by age and skill, with visible progress and family reports that explain what the child actually learned.',
        link: 'Learning framework',
      },
    },
  },

  showcase: {
    kicker: 'Real content before you sign in',
    heading: 'See exactly what you get',
    copy: 'Content pages, trailers and free samples are open to visitors without an account. Every title shows age, language and duration, and whether it is free or part of the subscription.',
    tabsAria: 'Content categories',
    exploreAll: 'Explore all content',
    access: { free: 'Free', premium: 'Premium', original: 'Majarra Original' },
    secondary: {
      trailer: 'Trailer',
      preview: 'Preview',
      sample: 'Audio sample',
      how: 'How to play',
      steps: 'Steps',
      review: 'Review process',
    },
    tabs: {
      top: 'Most watched',
      new: 'New stories',
      originals: 'Majarra Originals',
      science: 'Science',
      faith: 'Faith and values',
      games: 'Games and challenges',
    },
    items: {
      'kids-explorers-adventures': { title: 'Explorers’ Adventures', alt: 'Explorers’ Adventures series poster', meta: ['Series', 'Arabic · EN', '13 min'] },
      'adventures-of-numbers': { title: 'Adventures of Numbers', alt: 'Adventures of Numbers series poster', meta: ['Series', 'Arabic', '8 min'] },
      'discover-your-body': { title: 'Discover Your Body', alt: 'Discover Your Body series poster', meta: ['Educational', 'Arabic · FR', '11 min'] },
      'hekaya-wa-hikma': { title: 'A Tale and a Lesson', alt: 'A Tale and a Lesson series poster', meta: ['Values', 'Arabic', '7 min'] },
      'bedtime-stories': { title: 'Bedtime Stories', alt: 'Bedtime Stories poster', meta: ['Audio', 'Arabic · EN', '6 min'] },
      'try-it-at-home': { title: 'Try It at Home', alt: 'Try It at Home programme poster', meta: ['Activities', 'Arabic', '9 min'] },
      'book-arabic-letters': { title: 'My Arabic Letters', alt: 'My Arabic Letters book cover', meta: ['Picture book', '16 pages', '7 min read'] },
      'book-kindness': { title: 'The Seed of Kindness', alt: 'The Seed of Kindness book cover', meta: ['Picture book', '20 pages', 'Arabic · EN'] },
      'book-counting': { title: 'Count With Me', alt: 'Count With Me book cover', meta: ['Interactive story', '14 pages', 'Read to me'] },
      'book-nature': { title: 'Out in Nature', alt: 'Out in Nature book cover', meta: ['Picture book', '22 pages', 'Arabic · FR'] },
      'book-human-body': { title: 'A Journey Inside the Body', alt: 'A Journey Inside the Body book cover', meta: ['Illustrated book', '32 pages', 'Independent reading'] },
      'junior-solar-rover-guide': { title: 'The Solar Rover Guide', alt: 'The Solar Rover Guide cover', meta: ['Comic', '28 pages', 'Linked project'] },
      'junior-robo-codes': { title: 'Robo and the Codes', alt: 'Robo and the Codes series poster', meta: ['Series + game', 'Arabic · EN', '2 seasons'] },
      'junior-future-lab': { title: 'Future Lab', alt: 'Future Lab series poster', meta: ['Series + project', 'Arabic', '12 episodes'] },
      'junior-journey-civilizations': { title: 'Journey of Civilisations', alt: 'Journey of Civilisations series poster', meta: ['Series + comic', 'Arabic', '10 episodes'] },
      'preschool-luna-discovers-words': { title: 'Luna Discovers Words', alt: 'Luna Discovers Words series poster', meta: ['Series + stories', 'Arabic', 'Original character'] },
      'preschool-count-with-me': { title: 'Count With Me', alt: 'Count With Me series poster', meta: ['Series + game', 'Arabic', '16 episodes'] },
      'preschool-colors-around-us': { title: 'Colours Around Us', alt: 'Colours Around Us series poster', meta: ['Series + activity', 'Arabic', '14 episodes'] },
      'junior-science-in-a-minute': { title: 'Science in a Minute', alt: 'Science in a Minute programme poster', meta: ['Short episodes', 'Arabic', 'One minute'] },
      'junior-everyday-forces': { title: 'Forces Around Us', alt: 'Forces Around Us book cover', meta: ['Science comic', '26 pages', 'Arabic'] },
      'junior-science-evidence': { title: 'Scientific Evidence', alt: 'Scientific Evidence game cover', meta: ['Game', 'Inference skill', 'Works offline'] },
      'junior-project-solar-oven': { title: 'Solar Oven Project', alt: 'Solar Oven Project cover', meta: ['Project', '4 steps', 'With progress report'] },
      'kids-prophets-stories': { title: 'Stories of the Prophets', alt: 'Stories of the Prophets poster', meta: ['Series', 'Arabic', 'Scholar reviewed'] },
      'kids-quran-treasures': { title: 'Treasures of the Qur’an', alt: 'Treasures of the Qur’an poster', meta: ['Educational', 'Arabic', 'Sources cited'] },
      'preschool-noor-qalbi': { title: 'Light of My Heart', alt: 'Light of My Heart series poster', meta: ['Short series', 'Arabic', '5 min'] },
      'kids-prayer-step-by-step': { title: 'Prayer Step by Step', alt: 'Prayer Step by Step poster', meta: ['Educational', 'Arabic', 'Illustrated series'] },
      'junior-seerah-journey': { title: 'The Seerah Journey', alt: 'The Seerah Journey poster', meta: ['Series', 'Arabic', 'Scholar reviewed'] },
      'preschool-adhkar-manners': { title: 'My Adhkar and Manners', alt: 'My Adhkar and Manners poster', meta: ['Songs and manners', 'Arabic', '4 min'] },
      'game-letter-tracing': { title: 'Letter Tracing', alt: 'Letter Tracing game cover', meta: ['Game', 'Writing skill', 'Works offline'] },
      'game-number-maze': { title: 'Number Maze', alt: 'Number Maze game cover', meta: ['Game', 'Mental maths', '5 min'] },
      'game-shape-matching': { title: 'Shape Matching', alt: 'Shape Matching game cover', meta: ['Game', 'Visual perception', 'Works offline'] },
      'game-animal-memory': { title: 'Animal Memory', alt: 'Animal Memory game cover', meta: ['Game', 'Working memory', '4 min'] },
      'junior-code-sequence': { title: 'Code Sequence', alt: 'Code Sequence game cover', meta: ['Challenge', 'Logical thinking', 'Linked to Robo'] },
      'junior-circuit-builder': { title: 'Circuit Builder', alt: 'Circuit Builder game cover', meta: ['Challenge', 'Electrical engineering', 'Works offline'] },
    },
  },

  worlds: {
    kicker: 'Nine planets',
    heading: 'Majarra’s planets are not categories…',
    accent: 'they are worlds of knowledge',
    copy: 'Each planet is a world with its own content: episodes, stories, audio, games and projects tied to a clear skill. Pick a planet to see inside.',
    cta: 'Explore the planet',
    items: {
      language: {
        name: 'Planet of Language', short: 'Language', age: '3–12 years',
        desc: 'Letters, words, reading and expression, from a letter’s first sound to forming a full sentence and voicing an opinion.',
        types: ['Episodes', 'Picture books', 'Audio stories', 'Games'],
        picks: ['Luna Discovers Words', 'My Arabic Letters', 'Letter Tracing'],
      },
      numbers: {
        name: 'Planet of Numbers', short: 'Numbers', age: '3–12 years',
        desc: 'Counting, arithmetic, patterns and mathematical logic, through adventures and games that turn a number into a character.',
        types: ['Episodes', 'Games', 'Stories', 'Challenges'],
        picks: ['Adventures of Numbers', 'Count With Me', 'Number Maze'],
      },
      science: {
        name: 'Planet of Science', short: 'Science', age: '5–12 years',
        desc: 'The body, nature, space and forces, with safe experiments to do at home and projects that end in a tangible result.',
        types: ['Educational', 'Experiments', 'Comics', 'Projects'],
        picks: ['Discover Your Body', 'Science in a Minute', 'Solar Oven'],
      },
      stories: {
        name: 'Planet of Stories', short: 'Stories', age: '3–12 years',
        desc: 'Picture books, comics, audio stories and interactive tales in several languages, with four reading modes.',
        types: ['Picture books', 'Comics', 'Audio', 'Bedtime'],
        picks: ['Out in Nature', 'Bedtime Stories', 'The Seed of Kindness'],
      },
      creativity: {
        name: 'Planet of Creativity', short: 'Creativity', age: '3–12 years',
        desc: 'Drawing, colouring, building and making things from paper and household items, with activities to photograph and share with the family.',
        types: ['Activities', 'Projects', 'Games', 'Episodes'],
        picks: ['Colours Around Us', 'Paper Bridge', 'A Safe Experiment'],
      },
      skills: {
        name: 'Planet of Skills', short: 'Skills', age: '5–12 years',
        desc: 'Life and thinking skills: organising, problem solving, first steps in coding, and seeing a project through to the end.',
        types: ['Challenges', 'Projects', 'Episodes', 'Games'],
        picks: ['Robo and the Codes', 'Code Sequence', 'Circuit Builder'],
      },
      history: {
        name: 'Planet of History', short: 'History', age: '7–12 years',
        desc: 'Civilisations, inventions and timelines, told in a way that links what the child learns to what they see around them today.',
        types: ['Series', 'Comics', 'Games', 'Projects'],
        picks: ['Journey of Civilisations', 'Innovations of Civilisations', 'The Timeline'],
      },
      ourworld: {
        name: 'Planet of Our World', short: 'Our World', age: '4–12 years',
        desc: 'The environment, animals, countries and community, and the child’s responsibility toward the creatures and places around them.',
        types: ['Educational', 'Stories', 'Activities', 'Games'],
        picks: ['Explorers’ Adventures', 'Nature Watching', 'Animal Memory'],
      },
      faith: {
        name: 'Planet of Faith and Manners', short: 'Faith and Manners', age: '3–12 years',
        desc: 'Stories of the prophets, the seerah, manners and adhkar, with reviewed content whose sources appear on each title’s page.',
        types: ['Series', 'Songs', 'Stories', 'Manners'],
        picks: ['Stories of the Prophets', 'The Seerah Journey', 'My Adhkar and Manners'],
      },
    },
  },

  stories: {
    kicker: 'Planet of Stories',
    heading: 'A story your child reads… or one that reads itself',
    lead: 'Four reading modes for every stage, from the child who cannot read yet to the independent reader who prefers audio in the background.',
    cta: 'Explore the Planet of Stories',
    pageAlt: 'A page from the story Out in Nature',
    pageText: {
      before: '',
      highlight: 'Noha',
      after: ' went out to the garden and saw a tiny ant carrying a seed bigger than itself. She stopped and asked: how does it carry that all this way?',
    },
    audioLabel: 'Narration for page 4 of Out in Nature',
    audioPage: 'Page 4 of 22',
    audioVoice: 'Narrator',
    modes: [
      { title: 'I read alone', copy: 'Text only, no audio, for the independent reader' },
      { title: 'Read to me', copy: 'The narrator reads and pages turn automatically' },
      { title: 'Read with me', copy: 'The sentence is highlighted as it is read, so the eye can follow' },
      { title: 'Listen only', copy: 'The screen goes quiet and the audio carries the tale' },
    ],
    features: [
      'Separate narration for every page',
      'Arabic, English and French',
      'Automatic page turning',
      'Sentence highlighting while reading',
      'Bedtime stories',
      'Download to read offline',
      'Continue reading on another device',
      'Automatic cinematic view on TV',
    ],
  },

  ages: {
    kicker: 'Three experiences, one platform',
    heading: 'Content and interface change',
    accent: 'with your child’s age',
    copy: 'Enter the child’s age when creating their profile, and the content type, reading level, session length and game style are set accordingly. Change the age below to see how recommendations shift.',
    switchAria: 'Choose age track',
    samplesHeading: 'Suggested content for this age',
    specLabels: {
      content: 'Content type',
      reading: 'Reading level',
      session: 'Session length',
      games: 'Games',
      skills: 'Skills',
    },
    tracks: {
      preschool: {
        tabLabel: 'Little Explorer · 3–5',
        pill: '3–5 years',
        title: 'Little Explorer',
        copy: 'Generous space, large cards and few choices. The child does not need to read to navigate; sound and image lead the way.',
        specs: {
          content: 'Short calm episodes, songs, simple stories about colours, letters and numbers',
          reading: 'Pre-reading · “Read to me” by default with full audio support',
          session: '10–15 minutes, with no counters and no daily streaks pressuring the child',
          games: 'Drag and drop, matching, finger tracing, with large touch targets',
          skills: 'Recognising sounds, colours and shapes, and counting to 10',
        },
        samples: [
          { title: 'Luna Discovers Words', meta: 'Series · 5 min' },
          { title: 'Colours Around Us', meta: 'Series · 4 min' },
          { title: 'My Arabic Letters', meta: 'Story · Read to me' },
          { title: 'Shape Matching', meta: 'Game · Offline' },
        ],
      },
      kids: {
        tabLabel: 'Trailblazer · 6–8',
        pill: '6–8 years',
        title: 'Trailblazer',
        copy: 'Reading starts to stand on its own, content becomes series with consecutive episodes, with visible progress and mastery badges.',
        specs: {
          content: 'Adventure series, simplified science, stories about values and behaviour',
          reading: 'Early reading · “Read with me” with sentence highlighting',
          session: '15–25 minutes, with a short activity after the content',
          games: 'Puzzles, mazes, memory, reading and maths challenges',
          skills: 'Reading comprehension, addition and subtraction, scientific observation, social manners',
        },
        samples: [
          { title: 'Explorers’ Adventures', meta: 'Series · 13 min' },
          { title: 'Discover Your Body', meta: 'Educational · 11 min' },
          { title: 'The Seed of Kindness', meta: 'Story · Read with me' },
          { title: 'Number Maze', meta: 'Game · 5 min' },
        ],
      },
      junior: {
        tabLabel: 'Adventurer · 9–12',
        pill: '9–12 years',
        title: 'Adventurer',
        copy: 'A calmer, more mature interface, denser information, and real projects completed in steps rather than instant rewards.',
        specs: {
          content: 'Science and history series, comics, projects, logical thinking and coding',
          reading: 'Independent reading · longer texts and a clear type hierarchy',
          session: '25–40 minutes, or a project session spread over several days',
          games: 'Logic and coding challenges, circuit building, timelines, scientific evidence',
          skills: 'Critical thinking, problem solving, project management, writing and expression',
        },
        samples: [
          { title: 'Robo and the Codes', meta: 'Series + game' },
          { title: 'Journey of Civilisations', meta: 'Series · 10 episodes' },
          { title: 'Forces Around Us', meta: 'Comic · 26 pages' },
          { title: 'Paper Bridge Project', meta: 'Project · 4 steps' },
        ],
      },
    },
  },

  parents: {
    kicker: 'Safe and built for parents',
    heading: 'Your child explores freely… and you stay in control',
    lead: 'Safety at Majarra is not a slogan. It is real tools inside the app: who watches, what they watch, for how long, and what they gained.',
    features: [
      'A separate profile per child',
      'Age-appropriate content',
      'A parent PIN',
      'Screen-time limits',
      'Block or allow content',
      'Weekly reports',
      'Track reading and learning progress',
      'Control over downloads',
      'Manage linked devices',
      'Safe mode with no external links',
      'Limited, manually reviewed ads on Lite',
      'No ads on the Family plan',
    ],
    ctaPrimary: 'Parent dashboard',
    ctaSecondary: 'Safety and content review policy',
    dashBar: 'Parent dashboard · app.majarra.app',
    dashAlt: 'The parent dashboard showing each child’s progress, screen-time limits and the weekly report',
    miniOne: { caption: 'Weekly report', alt: 'Sample weekly report of a child’s progress' },
    miniTwo: { caption: 'Screen-time limits', alt: 'Screen showing screen-time limit settings' },
    captionStrong: 'Real screens from the app:',
    caption: 'Each child appears separately, with no merging of different ages into one score, and with the skills that need review made clear.',
  },

  learning: {
    kicker: 'The learning philosophy',
    heading: 'Learning without feeling',
    accent: 'like a lesson',
    copy: 'Majarra is not a digital school. It is an entertainment platform with organised educational value: every story, game or episode is tied to a skill, an objective, a level, a value and a follow-up activity.',
    flow: [
      { title: 'Watch an episode about space', copy: 'Enjoyable content first, with no heavy educational preamble' },
      { title: 'Read a short story', copy: 'The story revisits the idea in different language and context' },
      { title: 'Play a challenge', copy: 'Practical application that reveals what was understood and what needs review' },
      { title: 'Earn stars', copy: 'A reward for mastery, not for screen time' },
      { title: 'Progress appears in the parent report', copy: 'Written plainly, not as numbers without meaning' },
    ],
    tags: ['Skill', 'Learning objective', 'Age', 'Level', 'Value', 'Follow-up activity'],
  },

  identity: {
    kicker: 'Identity, language and values',
    heading: 'Content that loves our language and respects our values',
    lead: 'Simplified Modern Standard Arabic is the foundation, and values show up in behaviour inside the story rather than as a sermon at the child.',
    points: [
      'Simplified Modern Standard Arabic in text and audio',
      'Stories from Arab culture and its setting',
      'Positive values and behaviour inside the tale',
      'Reviewed faith content with sources cited',
      'Specialist review of religious content before publishing',
      'Learning Arabic for children outside the Arab world',
      'Choose text language and audio language independently',
    ],
    note: 'No child’s religiosity is measured and no “faith score” is shown. Faith content is a category inside Majarra like the other worlds, and stays part of the general experience rather than separated from it.',
    posters: [
      { caption: 'Light of My Heart · 3–5', alt: 'Light of My Heart series poster' },
      { caption: 'Stories of the Prophets · 6–8', alt: 'Stories of the Prophets poster' },
      { caption: 'The Seerah Journey · 9–12', alt: 'The Seerah Journey poster' },
      { caption: 'A Tale and a Lesson · Values', alt: 'A Tale and a Lesson poster' },
      { caption: 'Treasures of the Qur’an · 6–8', alt: 'Treasures of the Qur’an poster' },
      { caption: 'My Adhkar and Manners · 3–5', alt: 'My Adhkar and Manners poster' },
    ],
  },

  languages: {
    kicker: 'Three languages',
    heading: 'Language does not stop at the interface',
    copy: 'At Majarra language extends to video, stories, audio and text. Your child can read in one language and listen in another, or switch at any time without losing their place.',
    textLang: 'Text language',
    audioLang: 'Audio language',
    hint: 'Read in Arabic and listen in English, or switch language at any time. The setting is saved per child profile and applies to stories, episodes and audio.',
    chips: ['Written subtitles for episodes', 'Voice dubbing for stories', 'Full RTL and LTR interface'],
    audioPrefix: 'Audio:',
    idleText: 'Press to listen',
    source: 'Example from the story “Out in Nature” · page 4 of 22',
    narrationOf: (language: string) => `Narration in ${language}`,
  },

  devices: {
    kicker: 'Every device',
    heading: 'Start the story on the tablet, finish it on the TV',
    lead: 'Reading and viewing position travels with the child between devices, and the TV becomes a cinematic view with clear D-pad navigation.',
    items: [
      { name: 'Android', note: 'Phone and tablet' },
      { name: 'iPhone and iPad', note: 'iOS and iPadOS' },
      { name: 'Android TV', note: 'Full D-pad navigation' },
      { name: 'Apple TV', note: 'Later' },
      { name: 'Smart TV', note: 'Where supported' },
      { name: 'Web', note: 'app.majarra.app' },
    ],
    offlineStrong: 'Offline:',
    offline: 'Download episodes, stories and games on the Family plan, and watch in the car or on a plane without internet. Downloads stay under the parent’s control.',
    storeNote: 'Download the app',
    qr: 'Point your phone camera to download the Majarra app',
    qrLabel: 'QR code to download the Majarra app',
    tvAlt: 'Journey of Civilisations on a television screen',
    tabletAlt: 'A Journey Inside the Body on a tablet',
    phoneAlt: 'Robo and the Codes on a phone',
    floatTitle: '3 episodes downloaded',
    floatText: 'Ready to watch without internet',
  },

  originals: {
    kicker: 'Majarra Originals',
    heading: 'Worlds we produce ourselves,',
    accent: 'not just licensed content',
    copy: 'Series, stories, characters and games made by Majarra, connected in one world. The child watches the episode, reads its story, plays its game, then completes its challenge.',
    heroTitle: 'Robo and the Codes',
    heroAlt: 'A cinematic scene from the original series Robo and the Codes',
    heroCopy: 'An original series about logical thinking and coding, with the character “Robo” designed inside Majarra, alongside a comic, a sequencing game and a circuit-building project.',
    heroChips: ['9–12 years', '2 seasons', 'Arabic · English', 'Majarra Original'],
    steps: [
      { title: 'Watch the series', note: 'Episodes with characters and a complete world' },
      { title: 'Read the story', note: 'A comic that expands the episode’s events' },
      { title: 'Play the game', note: 'A game built on the series’ skill' },
      { title: 'Complete the challenge', note: 'A practical project with steps and a report' },
    ],
    cta: 'All Majarra Originals',
  },

  start: {
    kicker: 'Three steps',
    heading: 'How do you start?',
    copy: 'Two minutes is enough to create the family account and the first child profile. We do not ask for data we do not need, and we do not register the child under their full name.',
    steps: [
      { title: 'Create the family account', copy: 'A parent email and a PIN. The account belongs to the parent, and everything about payment, approvals and deletion stays on their screen, not in the child’s session.' },
      { title: 'Add your child’s profile, age and interests', copy: 'A nickname, birth month and year, and a few interests. Majarra picks the right track automatically, and you can change it at any time.' },
      { title: 'Start a personal, safe journey', copy: 'The child opens their profile and finds only content for their age. You follow along from the parent dashboard and set screen time, downloads and reports.' },
    ],
    cta: 'Start now',
  },

  plans: {
    kicker: 'Plans',
    heading: 'Choose what fits your family',
    copy: 'The price is visible from the first step and cancelling is available at any time. We do not hide plan differences and we do not ask for a card to start the free trial.',
    billingAria: 'Billing cycle',
    monthly: 'Monthly',
    yearly: 'Yearly',
    saveUpTo: 'Save up to 25%',
    currencyLabel: 'Currency',
    perMonth: '/ month',
    perYear: '/ year',
    freeAmount: 'Free',
    freeNote: 'Forever · no card',
    renewMonthly: 'Renews monthly · cancel anytime',
    renewYearlyWithSave: (percent: number) => `Renews yearly · save ${percent}% · cancel anytime`,
    renewYearly: 'Renews yearly · cancel anytime',
    compare: 'Detailed comparison table',
    compareHeaders: ['Feature', 'Free', 'Lite', 'Family'],
    note: 'The Family free trial is available without a card and ends automatically with no charge if you do not continue. Cancel from the parent dashboard at any time; the subscription runs until the end of the paid period.',
    noteFine: 'Prices shown are indicative before launch and will be finalised in your country’s currency when subscriptions open.',
    flagBest: 'Best for families',
    currencies: {
      SAR: 'Saudi Arabia · SAR',
      AED: 'UAE · AED',
      EGP: 'Egypt · EGP',
      USD: 'International · USD',
    },
    symbols: { SAR: 'SAR', AED: 'AED', EGP: 'EGP', USD: 'USD' },
    items: {
      free: {
        name: 'Free',
        tagline: 'Try Majarra with no card and no commitment, and see what the content is like.',
        cta: 'Start free',
        features: [
          'A limited library of episodes and stories',
          'Samples from every planet',
          'One child profile',
          'No download for offline viewing',
          'No detailed reports',
        ],
      },
      lite: {
        name: 'Majarra Lite',
        tagline: 'The full core library online, with safe and limited ads.',
        cta: 'Choose Lite',
        features: [
          'The full core library online',
          'Safe, limited, manually reviewed ads',
          'One child profile',
          'Simplified reports',
          'No offline download',
        ],
      },
      family: {
        name: 'Majarra Family',
        tagline: 'All of Majarra with no ads, for several children and devices, with offline download.',
        cta: 'Start the free trial',
        features: [
          'No ads at all',
          'All content: episodes, stories, audio and games',
          'Offline download for episodes and stories',
          'Up to 5 child profiles',
          'Up to 4 devices, two streams at once',
          'Advanced reports per child',
          'All available languages in text and audio',
        ],
      },
    },
    compareRows: [
      { feature: 'Library size', free: 'Samples', lite: 'Core library', family: 'All content' },
      { feature: 'Ads', free: 'Limited', lite: 'Limited and reviewed', family: 'None' },
      { feature: 'Child profiles', free: '1', lite: '1', family: 'Up to 5' },
      { feature: 'Linked devices', free: '1', lite: '2', family: 'Up to 4' },
      { feature: 'Simultaneous streams', free: '1', lite: '1', family: '2' },
      { feature: 'Video quality', free: 'SD', lite: 'HD', family: 'Full HD' },
      { feature: 'Offline download', free: 'No', lite: 'No', family: 'Yes' },
      { feature: 'Picture books and comics', free: 'Samples', lite: 'Yes', family: 'Yes' },
      { feature: 'Audio stories', free: 'Samples', lite: 'Yes', family: 'Yes' },
      { feature: 'Games and projects', free: 'Samples', lite: 'Partial', family: 'Full' },
      { feature: 'Parent reports', free: 'No', lite: 'Simplified', family: 'Advanced' },
      { feature: 'Screen-time limits', free: 'Yes', lite: 'Yes', family: 'Yes' },
      { feature: 'Text and audio languages', free: 'Arabic', lite: 'Arabic + one', family: 'All three' },
      { feature: 'TV support', free: 'No', lite: 'Yes', family: 'Yes' },
    ],
  },

  reviews: {
    kicker: 'Trust',
    heading: 'How we review content before your child sees it',
    copy: 'We have not launched publicly yet, so we show no ratings and no user counts. Instead we show our review process, and documented feedback from the early testing programme.',
    method: [
      { title: '1 · Educational review', copy: 'A childhood-education specialist reviews the learning objective, age suitability and language level before production.' },
      { title: '2 · Safety review', copy: 'Scenes, audio and effects are checked: no frightening scenes, no rapid flashing, and no external links inside the child’s experience.' },
      { title: '3 · Specialist review of religious content', copy: 'Faith content passes a specialist reviewer, and its sources are cited on the title’s own page.' },
    ],
    items: [
      {
        tag: 'From the early testing programme',
        quote: '“The first time my son sat and read on his own. ‘Read with me’ made him follow the sentence with his eyes instead of waiting for the audio.”',
        name: 'Mother of two', note: 'Riyadh · ages 5 and 8',
      },
      {
        tag: 'From the early testing programme',
        quote: '“The weekly report is what made the difference. Not a count of hours, but telling me which skill actually needs review.”',
        name: 'Father of three', note: 'Cairo · ages 4, 7 and 10',
      },
      {
        tag: 'Educational review',
        quote: '“Linking the episode to a story, then a game, then a home activity fixes the idea far better than rewatching the same content.”',
        name: 'Educational reviewer', note: 'Specialist in early childhood education',
      },
    ],
    honesty: 'We use no fabricated ratings or testimonials, and we show no figures such as “a million users” or “thousands of stories” before they are real and provable. The quotes above are from families who took part in early testing with their consent, under shortened names to protect their privacy.',
  },

  faq: {
    kicker: 'FAQ',
    heading: 'Questions parents ask before subscribing',
    helpCta: 'Help centre and all questions',
    items: [
      { q: 'What ages is it for?', a: 'From 3 to 12 years, across three tracks: 3–5, 6–8 and 9–12. The interface, reading level, session length and game types change with each track, and progress is kept when a child moves from one stage to the next.' },
      { q: 'Can the app be used for free?', a: 'Yes. The free plan is permanent and gives a limited library, samples from every planet and one child profile, with no bank card. The Family plan has a separate free trial that ends automatically with no charge.' },
      { q: 'Is the content safe?', a: 'Every title passes an educational review and a safety review before publishing: no frightening scenes, no rapid flashing, and no external links inside the child’s session. Purchases, approvals and deletion happen only on the parent’s screen.' },
      { q: 'Which languages are available?', a: 'Arabic, English and French. Language extends to the interface, video, stories and audio, and text language and audio language can be chosen independently for each child profile.' },
      { q: 'Does it work offline?', a: 'Yes on the Family plan: download episodes, stories and some games to watch and read without internet. Downloads are under the parent’s control and can be limited or blocked per child profile.' },
      { q: 'How many devices?', a: 'Free allows one device, Lite two, and Family up to four devices with two simultaneous streams. Managing and removing devices is done from the parent dashboard.' },
      { q: 'Can I create a profile for each child?', a: 'Yes, up to five profiles on the Family plan. Each profile has its own age track, recommendations, progress, favourites and reports, and results from different ages are never merged into one score.' },
      { q: 'What is the difference between Lite and Family?', a: 'Lite is the core library online for one child with limited ads and simplified reports. Family has no ads, all content including stories, audio and games, plus offline download, several profiles and devices, and advanced reports.' },
      { q: 'Are there ads?', a: 'On Free and Lite there are limited, manually reviewed ads that do not target the child behaviourally and do not take them out of the app. The Family plan has no ads at all.' },
      { q: 'How do parent reports work?', a: 'A weekly report per child shows what they watched, read and played, which skills they mastered and which need review, and reading progress. It is written plainly without jargon, and shows no ranking or comparison with other children.' },
      { q: 'How is faith content chosen?', a: 'It passes a specialist reviewer before publishing, and its sources are cited on the title’s page. It appears as a category inside Majarra like the other worlds, and is never used to measure a child’s religiosity or to show any “faith score”.' },
      { q: 'Can I cancel the subscription?', a: 'Yes, from the parent dashboard at any time in two steps, with no call or message. Your access continues until the end of the paid period and no renewal is charged after that.' },
      { q: 'Does it work on TV?', a: 'Yes on Android TV with full D-pad navigation, larger text and horizontal rows suited to viewing distance. Apple TV comes later, and Smart TV where supported. Pairing uses a QR code or a short code from the parent’s screen.' },
      { q: 'Can the age or reading level be changed?', a: 'Yes. You can adjust the birth date or raise the reading level manually if your child is ahead, or lower it for a calmer experience. The change applies to recommendations immediately and keeps earlier progress.' },
    ],
  },

  download: {
    heading: 'Start your child’s journey in Majarra today',
    copy: 'Create the family account for free, add your child’s profile, and let them explore a safe world of stories and knowledge.',
    ctaPrimary: 'Start your free trial',
    ctaSecondary: 'Download the app',
    fine: 'No bank card · cancel anytime · available on phone, tablet, TV and web',
  },

  partners: {
    kicker: 'Partnerships',
    heading: 'Work with Majarra',
    accent: 'schools, nurseries and content makers',
    copy: 'We work with schools, nurseries, publishers, content producers and voice artists. Leave your details and we will reply with clear next steps.',
    audiences: [
      { title: 'Schools and kindergartens', copy: 'Classroom accounts, curriculum-linked content, and teacher reports instead of family reports.' },
      { title: 'Nurseries and centres', copy: 'Licences for group viewing in the classroom, and short content suited to circle time.' },
      { title: 'Publishers and producers', copy: 'License your work inside Majarra, or produce an original series with us to our educational specification.' },
      { title: 'Voice artists and creators', copy: 'Voice recording in Modern Standard Arabic, English or French, plus illustration and animation.' },
    ],
    form: {
      heading: 'Request a collaboration',
      lead: 'We usually reply within two working days. We do not share your details with anyone else.',
      type: 'Organisation type',
      types: {
        school: 'School',
        nursery: 'Nursery or kindergarten',
        publisher: 'Publisher',
        producer: 'Content producer',
        creator: 'Voice artist or creator',
        other: 'Other',
      },
      name: 'Name',
      namePlaceholder: 'Your full name',
      organization: 'Organisation name',
      organizationPlaceholder: 'School or company name',
      email: 'Email',
      emailPlaceholder: 'name@example.com',
      phone: 'Phone',
      optional: 'optional',
      phonePlaceholder: '+20 100 000 0000',
      country: 'Country',
      countryPlaceholder: 'Egypt, Saudi Arabia…',
      message: 'Collaboration details',
      messagePlaceholder: 'Briefly describe the collaboration you have in mind, and the number of children or volume of content if relevant.',
      submit: 'Send request',
      submitting: 'Sending…',
      successTitle: 'We received your request',
      successBody: 'We will review it and reply to your email within two working days. You can send another request if you need to.',
      sendAnother: 'Send another request',
      errorGeneric: 'Could not send the request. Please try again in a moment.',
      errorEmail: 'Enter a valid email address.',
      errorRequired: 'Please complete the required fields first.',
      errorRate: 'Too many requests. Wait a minute and try again.',
      privacy: 'By using this form you agree that we may contact you about your request only.',
    },
  },

  footer: {
    about: 'A safe Arabic-first platform for children aged 3 to 12, bringing watching, reading, listening, playing and learning into one experience, with real tools for parents.',
    columns: {
      majarra: { title: 'Majarra', links: ['About Majarra', 'Our mission', 'Review team', 'Careers', 'Contact us'] },
      discover: { title: 'Discover', links: ['Planets', 'Series', 'Stories', 'Games', 'Audio content', 'Majarra Originals'] },
      parents: { title: 'For parents', links: ['Safety', 'Learning', 'Parental controls', 'Plans', 'Devices', 'Help centre'] },
      partners: { title: 'Partnerships', links: ['Content producers', 'Publishers', 'Schools', 'Voice artists and creators', 'Sponsorships'] },
      legal: { title: 'Legal', links: ['Privacy', 'Children’s privacy', 'Terms', 'Cookie policy', 'Ads policy', 'Account deletion request', 'Content rights'] },
    },
    langLabel: 'Language',
    stores: 'App stores',
    social: ['Majarra on YouTube', 'Majarra on Instagram', 'Majarra on X', 'Majarra on TikTok'],
    rights: 'All rights reserved',
  },
}
