import type { LandingCopy } from './ar'

/**
 * النصوص الفرنسية. النوع LandingCopy يفرض تطابق المفاتيح مع العربية،
 * فأي مفتاح ناقص أو زائد يوقف البناء.
 * لا حاجة لعزل الاتجاه هنا لأن السياق LTR أصلًا.
 */
export const fr: LandingCopy = {
  meta: {
    title: 'Majarra | Tout un monde d’histoires et de savoir pour votre enfant',
    description:
      'Une plateforme sûre, pensée d’abord pour l’arabe, pour les 3 à 12 ans : séries, albums illustrés, histoires audio, jeux et contenus éducatifs.',
  },

  common: {
    skip: 'Aller au contenu',
    brandLabel: 'Majarra, page d’accueil',
    langAria: 'Choisir la langue',
    menuOpen: 'Ouvrir le menu',
    menuClose: 'Fermer le menu',
    login: 'Se connecter',
    startFree: 'Commencer gratuitement',
    details: 'Détails',
  },

  nav: {
    home: 'Accueil',
    discover: 'Découvrir',
    worlds: 'Planètes',
    parents: 'Pour les parents',
    plans: 'Formules',
    devices: 'Appareils',
    partners: 'Partenariats',
    discoverAria: 'Menu Découvrir',
    mainAria: 'Navigation principale',
  },

  mega: {
    watch: { title: 'Regarder', links: ['Séries', 'Films', 'Épisodes courts', 'Contenus éducatifs'] },
    read: { title: 'Lire', links: ['Albums illustrés', 'Bandes dessinées', 'Livres', 'Planète des Histoires'] },
    listen: { title: 'Écouter', links: ['Histoires audio', 'Avant de dormir', 'Chansons'] },
    play: { title: 'Jouer', links: ['Jeux éducatifs', 'Défis', 'Activités'] },
    learn: { title: 'Apprendre', links: ['Langue', 'Sciences', 'Nombres', 'Histoire', 'Compétences'] },
  },

  hero: {
    eyebrow: 'Une plateforme sûre, pensée d’abord pour l’arabe, pour les enfants de 3 à 12 ans',
    slides: [
      {
        title: 'Tout un monde d’histoires',
        accent: 'et de savoir pour votre enfant',
        copy: 'Regardez des séries, lisez des histoires, écoutez des contes et jouez à des jeux éducatifs sûrs, en arabe et dans d’autres langues.',
      },
      {
        title: 'Une histoire que votre enfant lit…',
        accent: 'ou qui se lit toute seule',
        copy: 'Albums et bandes dessinées avec quatre modes de lecture, une narration pour chaque page, la phrase surlignée pendant la lecture et le téléchargement hors ligne.',
      },
      {
        title: 'Votre enfant explore librement…',
        accent: 'et vous gardez la main',
        copy: 'Un profil distinct par enfant, des contenus adaptés à l’âge, un code parental, des limites de temps d’écran et un rapport hebdomadaire clair sur la lecture et les apprentissages.',
      },
    ],
    notes: ['Sûr pour les enfants', 'Sans publicité sur la formule Famille', 'Fonctionne sur tous vos appareils'],
    ctaPrimary: 'Commencer l’essai gratuit',
    ctaSecondary: 'Découvrir le contenu de Majarra',
    dotsAria: 'Diapositives',
    slideAria: (index: number, title: string) => `Diapositive ${index} : ${title}`,
    tvAlt: 'Une scène des Aventures des explorateurs affichée sur un écran de télévision',
    tabletAlt: 'Un album illustré affiché sur une tablette',
    phoneAlt: 'Affiche de la série Luna découvre les mots sur un téléphone',
    floatA: { title: 'Commencez sur la tablette', text: 'et continuez sur la télévision à la même page' },
    floatB: { title: 'Un rapport parental hebdomadaire', text: 'la progression en lecture et en compétences, clairement' },
  },

  trust: [
    'Convient aux 3–12 ans',
    'Contenus arabes et internationaux',
    'Plusieurs profils d’enfants',
    'Téléchargement pour le hors ligne',
    'Téléphone, tablette et télévision',
    'Contrôle parental et rapports',
  ],

  pillars: {
    kicker: 'Cinq piliers, une seule plateforme',
    heading: 'Tout ce que votre enfant aime',
    accent: 'au même endroit',
    copy: 'Majarra n’est pas une simple vidéothèque. Regarder, lire, écouter, jouer et apprendre sont reliés dans une seule expérience, conçue pour l’âge de l’enfant.',
    items: {
      watch: {
        title: 'Regarder',
        copy: 'Séries, films, épisodes courts et contenus éducatifs adaptés à l’âge de votre enfant, en haute qualité, avec des saisons et des épisodes clairs.',
        link: 'Parcourir les séries',
      },
      read: {
        title: 'Lire',
        copy: 'Albums illustrés et bandes dessinées multilingues, à lire seul ou avec le narrateur, avec la phrase surlignée pendant la lecture.',
        link: 'Parcourir les histoires',
      },
      listen: {
        title: 'Écouter',
        copy: 'Histoires audio, contes du soir et chansons, avec des voix et des effets calmes, à un volume et un ton adaptés au sommeil.',
        link: 'Parcourir l’audio',
      },
      play: {
        title: 'Jouer',
        copy: 'Des jeux et des défis qui relient le plaisir aux compétences, sans chronomètre sous pression et sans récompense liée au temps d’écran.',
        link: 'Parcourir les jeux',
      },
      learn: {
        title: 'Apprendre',
        copy: 'Des contenus organisés par âge et par compétence, avec une progression visible et des rapports familiaux qui expliquent ce que l’enfant a réellement appris.',
        link: 'Cadre pédagogique',
      },
    },
  },

  showcase: {
    kicker: 'Du vrai contenu avant même de vous connecter',
    heading: 'Voyez exactement ce que vous obtenez',
    copy: 'Les pages de contenu, les bandes-annonces et les extraits gratuits sont ouverts aux visiteurs sans compte. Chaque titre indique l’âge, la langue et la durée, et s’il est gratuit ou inclus dans l’abonnement.',
    tabsAria: 'Catégories de contenu',
    exploreAll: 'Découvrir tout le contenu',
    access: { free: 'Gratuit', premium: 'Premium', original: 'Original Majarra' },
    secondary: {
      trailer: 'Bande-annonce',
      preview: 'Aperçu',
      sample: 'Extrait audio',
      how: 'Comment jouer',
      steps: 'Étapes',
      review: 'Processus de révision',
    },
    tabs: {
      top: 'Les plus regardés',
      new: 'Nouvelles histoires',
      originals: 'Originaux Majarra',
      science: 'Sciences',
      faith: 'Foi et valeurs',
      games: 'Jeux et défis',
    },
    items: {
      'kids-explorers-adventures': { title: 'Les aventures des explorateurs', alt: 'Affiche de la série Les aventures des explorateurs', meta: ['Série', 'Arabe · EN', '13 min'] },
      'adventures-of-numbers': { title: 'Les aventures des nombres', alt: 'Affiche de la série Les aventures des nombres', meta: ['Série', 'Arabe', '8 min'] },
      'discover-your-body': { title: 'Découvre ton corps', alt: 'Affiche de la série Découvre ton corps', meta: ['Éducatif', 'Arabe · FR', '11 min'] },
      'hekaya-wa-hikma': { title: 'Un conte et une leçon', alt: 'Affiche de la série Un conte et une leçon', meta: ['Valeurs', 'Arabe', '7 min'] },
      'bedtime-stories': { title: 'Histoires du soir', alt: 'Affiche de Histoires du soir', meta: ['Audio', 'Arabe · EN', '6 min'] },
      'try-it-at-home': { title: 'Essaie à la maison', alt: 'Affiche du programme Essaie à la maison', meta: ['Activités', 'Arabe', '9 min'] },
      'book-arabic-letters': { title: 'Mes lettres arabes', alt: 'Couverture du livre Mes lettres arabes', meta: ['Album illustré', '16 pages', '7 min de lecture'] },
      'book-kindness': { title: 'La graine de la bonté', alt: 'Couverture du livre La graine de la bonté', meta: ['Album illustré', '20 pages', 'Arabe · EN'] },
      'book-counting': { title: 'Compte avec moi', alt: 'Couverture du livre Compte avec moi', meta: ['Histoire interactive', '14 pages', 'Lis-moi l’histoire'] },
      'book-nature': { title: 'Dehors, dans la nature', alt: 'Couverture du livre Dehors, dans la nature', meta: ['Album illustré', '22 pages', 'Arabe · FR'] },
      'book-human-body': { title: 'Voyage à l’intérieur du corps', alt: 'Couverture du livre Voyage à l’intérieur du corps', meta: ['Livre illustré', '32 pages', 'Lecture autonome'] },
      'junior-solar-rover-guide': { title: 'Le guide du rover solaire', alt: 'Couverture de Le guide du rover solaire', meta: ['Bande dessinée', '28 pages', 'Projet associé'] },
      'junior-robo-codes': { title: 'Robo et les codes', alt: 'Affiche de la série Robo et les codes', meta: ['Série + jeu', 'Arabe · EN', '2 saisons'] },
      'junior-future-lab': { title: 'Le labo du futur', alt: 'Affiche de la série Le labo du futur', meta: ['Série + projet', 'Arabe', '12 épisodes'] },
      'junior-journey-civilizations': { title: 'Le voyage des civilisations', alt: 'Affiche de la série Le voyage des civilisations', meta: ['Série + BD', 'Arabe', '10 épisodes'] },
      'preschool-luna-discovers-words': { title: 'Luna découvre les mots', alt: 'Affiche de la série Luna découvre les mots', meta: ['Série + histoires', 'Arabe', 'Personnage original'] },
      'preschool-count-with-me': { title: 'Compte avec moi', alt: 'Affiche de la série Compte avec moi', meta: ['Série + jeu', 'Arabe', '16 épisodes'] },
      'preschool-colors-around-us': { title: 'Les couleurs autour de nous', alt: 'Affiche de la série Les couleurs autour de nous', meta: ['Série + activité', 'Arabe', '14 épisodes'] },
      'junior-science-in-a-minute': { title: 'La science en une minute', alt: 'Affiche du programme La science en une minute', meta: ['Épisodes courts', 'Arabe', 'Une minute'] },
      'junior-everyday-forces': { title: 'Les forces autour de nous', alt: 'Couverture du livre Les forces autour de nous', meta: ['BD scientifique', '26 pages', 'Arabe'] },
      'junior-science-evidence': { title: 'La preuve scientifique', alt: 'Couverture du jeu La preuve scientifique', meta: ['Jeu', 'Déduction', 'Fonctionne hors ligne'] },
      'junior-project-solar-oven': { title: 'Projet four solaire', alt: 'Couverture de Projet four solaire', meta: ['Projet', '4 étapes', 'Avec rapport de progression'] },
      'kids-prophets-stories': { title: 'Les histoires des prophètes', alt: 'Affiche de Les histoires des prophètes', meta: ['Série', 'Arabe', 'Validé par un spécialiste'] },
      'kids-quran-treasures': { title: 'Les trésors du Coran', alt: 'Affiche de Les trésors du Coran', meta: ['Éducatif', 'Arabe', 'Sources citées'] },
      'preschool-noor-qalbi': { title: 'La lumière de mon cœur', alt: 'Affiche de la série La lumière de mon cœur', meta: ['Série courte', 'Arabe', '5 min'] },
      'kids-prayer-step-by-step': { title: 'La prière pas à pas', alt: 'Affiche de La prière pas à pas', meta: ['Éducatif', 'Arabe', 'Série illustrée'] },
      'junior-seerah-journey': { title: 'Le voyage de la Sîra', alt: 'Affiche de Le voyage de la Sîra', meta: ['Série', 'Arabe', 'Validé par un spécialiste'] },
      'preschool-adhkar-manners': { title: 'Mes invocations et mes bonnes manières', alt: 'Affiche de Mes invocations et mes bonnes manières', meta: ['Chansons et manières', 'Arabe', '4 min'] },
      'game-letter-tracing': { title: 'Tracé des lettres', alt: 'Couverture du jeu Tracé des lettres', meta: ['Jeu', 'Écriture', 'Fonctionne hors ligne'] },
      'game-number-maze': { title: 'Le labyrinthe des nombres', alt: 'Couverture du jeu Le labyrinthe des nombres', meta: ['Jeu', 'Calcul mental', '5 min'] },
      'game-shape-matching': { title: 'Associer les formes', alt: 'Couverture du jeu Associer les formes', meta: ['Jeu', 'Perception visuelle', 'Fonctionne hors ligne'] },
      'game-animal-memory': { title: 'Mémo des animaux', alt: 'Couverture du jeu Mémo des animaux', meta: ['Jeu', 'Mémoire de travail', '4 min'] },
      'junior-code-sequence': { title: 'La séquence de code', alt: 'Couverture du jeu La séquence de code', meta: ['Défi', 'Pensée logique', 'Lié à Robo'] },
      'junior-circuit-builder': { title: 'Constructeur de circuits', alt: 'Couverture du jeu Constructeur de circuits', meta: ['Défi', 'Génie électrique', 'Fonctionne hors ligne'] },
    },
  },

  worlds: {
    kicker: 'Neuf planètes',
    heading: 'Les planètes de Majarra ne sont pas des catégories…',
    accent: 'ce sont des mondes de savoir',
    copy: 'Chaque planète est un monde avec son propre contenu : épisodes, histoires, audio, jeux et projets liés à une compétence claire. Choisissez une planète pour voir l’intérieur.',
    cta: 'Explorer la planète',
    items: {
      language: {
        name: 'Planète de la Langue', short: 'Langue', age: '3–12 ans',
        desc: 'Lettres, mots, lecture et expression, du premier son d’une lettre jusqu’à former une phrase complète et exprimer une opinion.',
        types: ['Épisodes', 'Albums illustrés', 'Histoires audio', 'Jeux'],
        picks: ['Luna découvre les mots', 'Mes lettres arabes', 'Tracé des lettres'],
      },
      numbers: {
        name: 'Planète des Nombres', short: 'Nombres', age: '3–12 ans',
        desc: 'Compter, calculer, repérer des motifs et raisonner en mathématiques, à travers des aventures et des jeux qui transforment un nombre en personnage.',
        types: ['Épisodes', 'Jeux', 'Histoires', 'Défis'],
        picks: ['Les aventures des nombres', 'Compte avec moi', 'Le labyrinthe des nombres'],
      },
      science: {
        name: 'Planète des Sciences', short: 'Sciences', age: '5–12 ans',
        desc: 'Le corps, la nature, l’espace et les forces, avec des expériences sûres à faire à la maison et des projets qui aboutissent à un résultat concret.',
        types: ['Éducatif', 'Expériences', 'Bandes dessinées', 'Projets'],
        picks: ['Découvre ton corps', 'La science en une minute', 'Four solaire'],
      },
      stories: {
        name: 'Planète des Histoires', short: 'Histoires', age: '3–12 ans',
        desc: 'Albums illustrés, bandes dessinées, histoires audio et contes interactifs en plusieurs langues, avec quatre modes de lecture.',
        types: ['Albums illustrés', 'Bandes dessinées', 'Audio', 'Avant de dormir'],
        picks: ['Dehors, dans la nature', 'Histoires du soir', 'La graine de la bonté'],
      },
      creativity: {
        name: 'Planète de la Créativité', short: 'Créativité', age: '3–12 ans',
        desc: 'Dessiner, colorier, construire et fabriquer avec du papier et des objets du quotidien, avec des activités à photographier et à partager en famille.',
        types: ['Activités', 'Projets', 'Jeux', 'Épisodes'],
        picks: ['Les couleurs autour de nous', 'Le pont en papier', 'Une expérience sûre'],
      },
      skills: {
        name: 'Planète des Compétences', short: 'Compétences', age: '5–12 ans',
        desc: 'Compétences de vie et de réflexion : s’organiser, résoudre des problèmes, faire ses premiers pas en programmation et mener un projet jusqu’au bout.',
        types: ['Défis', 'Projets', 'Épisodes', 'Jeux'],
        picks: ['Robo et les codes', 'La séquence de code', 'Constructeur de circuits'],
      },
      history: {
        name: 'Planète de l’Histoire', short: 'Histoire', age: '7–12 ans',
        desc: 'Civilisations, inventions et frises chronologiques, racontées de façon à relier ce que l’enfant apprend à ce qu’il voit aujourd’hui autour de lui.',
        types: ['Séries', 'Bandes dessinées', 'Jeux', 'Projets'],
        picks: ['Le voyage des civilisations', 'Les innovations des civilisations', 'La frise du temps'],
      },
      ourworld: {
        name: 'Planète de Notre Monde', short: 'Notre Monde', age: '4–12 ans',
        desc: 'L’environnement, les animaux, les pays et la communauté, et la responsabilité de l’enfant envers les êtres et les lieux qui l’entourent.',
        types: ['Éducatif', 'Histoires', 'Activités', 'Jeux'],
        picks: ['Les aventures des explorateurs', 'Observer la nature', 'Mémo des animaux'],
      },
      faith: {
        name: 'Planète de la Foi et des Bonnes Manières', short: 'Foi et Manières', age: '3–12 ans',
        desc: 'Histoires des prophètes, Sîra, bonnes manières et invocations, avec des contenus révisés dont les sources figurent sur la page de chaque titre.',
        types: ['Séries', 'Chansons', 'Histoires', 'Bonnes manières'],
        picks: ['Les histoires des prophètes', 'Le voyage de la Sîra', 'Mes invocations et mes bonnes manières'],
      },
    },
  },

  stories: {
    kicker: 'Planète des Histoires',
    heading: 'Une histoire que votre enfant lit… ou qui se lit toute seule',
    lead: 'Quatre modes de lecture pour chaque étape, de l’enfant qui ne lit pas encore au lecteur autonome qui préfère l’audio en fond.',
    cta: 'Explorer la Planète des Histoires',
    pageAlt: 'Une page de l’histoire Dehors, dans la nature',
    pageText: {
      before: '',
      highlight: 'Noha',
      after: ' est sortie au jardin et a vu une toute petite fourmi porter une graine plus grosse qu’elle. Elle s’est arrêtée et a demandé : comment fait-elle pour porter cela sur tout ce chemin ?',
    },
    audioLabel: 'Narration de la page 4 de Dehors, dans la nature',
    audioPage: 'Page 4 sur 22',
    audioVoice: 'Narratrice',
    modes: [
      { title: 'Je lis seul', copy: 'Texte seulement, sans audio, pour le lecteur autonome' },
      { title: 'Lis-moi l’histoire', copy: 'Le narrateur lit et les pages tournent automatiquement' },
      { title: 'Lis avec moi', copy: 'La phrase est surlignée au fil de la lecture, pour que l’œil puisse suivre' },
      { title: 'Écouter seulement', copy: 'L’écran se met en veille et l’audio porte le récit' },
    ],
    features: [
      'Une narration distincte pour chaque page',
      'Arabe, anglais et français',
      'Tournage automatique des pages',
      'Phrase surlignée pendant la lecture',
      'Histoires du soir',
      'Téléchargement pour lire hors ligne',
      'Reprendre la lecture sur un autre appareil',
      'Vue cinématique automatique sur la télévision',
    ],
  },

  ages: {
    kicker: 'Trois expériences, une seule plateforme',
    heading: 'Le contenu et l’interface changent',
    accent: 'avec l’âge de votre enfant',
    copy: 'Indiquez l’âge de l’enfant à la création de son profil : le type de contenu, le niveau de lecture, la durée des sessions et le style des jeux s’ajustent en conséquence. Changez l’âge ci-dessous pour voir comment les recommandations évoluent.',
    switchAria: 'Choisir la tranche d’âge',
    samplesHeading: 'Contenus suggérés pour cet âge',
    specLabels: {
      content: 'Type de contenu',
      reading: 'Niveau de lecture',
      session: 'Durée de session',
      games: 'Jeux',
      skills: 'Compétences',
    },
    tracks: {
      preschool: {
        tabLabel: 'Petit explorateur · 3–5',
        pill: '3–5 ans',
        title: 'Petit explorateur',
        copy: 'De l’espace généreux, de grandes cartes et peu de choix. L’enfant n’a pas besoin de lire pour naviguer : le son et l’image le guident.',
        specs: {
          content: 'Épisodes courts et calmes, chansons, histoires simples sur les couleurs, les lettres et les nombres',
          reading: 'Pré-lecture · « Lis-moi l’histoire » par défaut, avec un accompagnement audio complet',
          session: '10–15 minutes, sans compteurs ni séries quotidiennes qui mettent l’enfant sous pression',
          games: 'Glisser-déposer, associations, tracé au doigt, avec de grandes zones tactiles',
          skills: 'Reconnaître les sons, les couleurs et les formes, et compter jusqu’à 10',
        },
        samples: [
          { title: 'Luna découvre les mots', meta: 'Série · 5 min' },
          { title: 'Les couleurs autour de nous', meta: 'Série · 4 min' },
          { title: 'Mes lettres arabes', meta: 'Histoire · Lis-moi l’histoire' },
          { title: 'Associer les formes', meta: 'Jeu · Hors ligne' },
        ],
      },
      kids: {
        tabLabel: 'Éclaireur · 6–8',
        pill: '6–8 ans',
        title: 'Éclaireur',
        copy: 'La lecture commence à tenir seule, le contenu devient des séries aux épisodes successifs, avec une progression visible et des badges de maîtrise.',
        specs: {
          content: 'Séries d’aventure, sciences simplifiées, histoires sur les valeurs et le comportement',
          reading: 'Lecture débutante · « Lis avec moi » avec la phrase surlignée',
          session: '15–25 minutes, avec une courte activité après le contenu',
          games: 'Casse-têtes, labyrinthes, mémo, défis de lecture et de calcul',
          skills: 'Compréhension de lecture, addition et soustraction, observation scientifique, savoir-vivre',
        },
        samples: [
          { title: 'Les aventures des explorateurs', meta: 'Série · 13 min' },
          { title: 'Découvre ton corps', meta: 'Éducatif · 11 min' },
          { title: 'La graine de la bonté', meta: 'Histoire · Lis avec moi' },
          { title: 'Le labyrinthe des nombres', meta: 'Jeu · 5 min' },
        ],
      },
      junior: {
        tabLabel: 'Aventurier · 9–12',
        pill: '9–12 ans',
        title: 'Aventurier',
        copy: 'Une interface plus calme et plus mature, une information plus dense, et de vrais projets menés par étapes plutôt que des récompenses instantanées.',
        specs: {
          content: 'Séries scientifiques et historiques, bandes dessinées, projets, pensée logique et programmation',
          reading: 'Lecture autonome · textes plus longs et hiérarchie typographique claire',
          session: '25–40 minutes, ou une session de projet répartie sur plusieurs jours',
          games: 'Défis de logique et de code, construction de circuits, frises chronologiques, preuves scientifiques',
          skills: 'Pensée critique, résolution de problèmes, gestion de projet, écriture et expression',
        },
        samples: [
          { title: 'Robo et les codes', meta: 'Série + jeu' },
          { title: 'Le voyage des civilisations', meta: 'Série · 10 épisodes' },
          { title: 'Les forces autour de nous', meta: 'BD · 26 pages' },
          { title: 'Projet pont en papier', meta: 'Projet · 4 étapes' },
        ],
      },
    },
  },

  parents: {
    kicker: 'Sûr et pensé pour les parents',
    heading: 'Votre enfant explore librement… et vous gardez la main',
    lead: 'Chez Majarra, la sécurité n’est pas un slogan. Ce sont de vrais outils dans l’application : qui regarde, quoi, pendant combien de temps, et ce qu’il en a retiré.',
    features: [
      'Un profil distinct par enfant',
      'Des contenus adaptés à l’âge',
      'Un code parental',
      'Des limites de temps d’écran',
      'Bloquer ou autoriser des contenus',
      'Rapports hebdomadaires',
      'Suivi de la progression en lecture et en apprentissage',
      'Contrôle des téléchargements',
      'Gestion des appareils liés',
      'Mode sûr sans liens externes',
      'Publicités limitées et vérifiées manuellement sur Lite',
      'Aucune publicité sur la formule Famille',
    ],
    ctaPrimary: 'Espace parents',
    ctaSecondary: 'Politique de sécurité et de révision des contenus',
    dashBar: 'Espace parents · app.majarra.app',
    dashAlt: 'L’espace parents affichant la progression de chaque enfant, les limites de temps d’écran et le rapport hebdomadaire',
    miniOne: { caption: 'Rapport hebdomadaire', alt: 'Exemple de rapport hebdomadaire de progression d’un enfant' },
    miniTwo: { caption: 'Limites de temps d’écran', alt: 'Écran des réglages des limites de temps d’écran' },
    captionStrong: 'De vrais écrans de l’application :',
    caption: 'Chaque enfant apparaît séparément, sans fusionner des âges différents dans un même score, et les compétences à revoir sont clairement indiquées.',
  },

  learning: {
    kicker: 'La philosophie d’apprentissage',
    heading: 'Apprendre sans avoir l’impression',
    accent: 'd’être en cours',
    copy: 'Majarra n’est pas une école numérique. C’est une plateforme de divertissement à valeur éducative organisée : chaque histoire, jeu ou épisode est relié à une compétence, un objectif, un niveau, une valeur et une activité de prolongement.',
    flow: [
      { title: 'Regarder un épisode sur l’espace', copy: 'Du contenu plaisant d’abord, sans lourde introduction pédagogique' },
      { title: 'Lire une courte histoire', copy: 'L’histoire reprend l’idée dans une autre langue et un autre contexte' },
      { title: 'Jouer à un défi', copy: 'Une application pratique qui révèle ce qui est compris et ce qui reste à revoir' },
      { title: 'Gagner des étoiles', copy: 'Une récompense pour la maîtrise, pas pour le temps d’écran' },
      { title: 'La progression apparaît dans le rapport parental', copy: 'Rédigée simplement, pas en chiffres sans signification' },
    ],
    tags: ['Compétence', 'Objectif d’apprentissage', 'Âge', 'Niveau', 'Valeur', 'Activité de prolongement'],
  },

  identity: {
    kicker: 'Identité, langue et valeurs',
    heading: 'Des contenus qui aiment notre langue et respectent nos valeurs',
    lead: 'L’arabe standard moderne simplifié est la base, et les valeurs apparaissent dans le comportement au sein de l’histoire plutôt qu’en leçon de morale adressée à l’enfant.',
    points: [
      'Arabe standard moderne simplifié à l’écrit et à l’oral',
      'Des histoires issues de la culture arabe et de son cadre',
      'Des valeurs et des comportements positifs au cœur du récit',
      'Des contenus religieux révisés avec citation des sources',
      'Révision par un spécialiste des contenus religieux avant publication',
      'Apprentissage de l’arabe pour les enfants hors du monde arabe',
      'Choix indépendant de la langue du texte et de la langue audio',
    ],
    note: 'La religiosité d’aucun enfant n’est mesurée et aucun « score de foi » n’est affiché. Les contenus religieux forment une catégorie de Majarra comme les autres mondes, et restent intégrés à l’expérience générale au lieu d’en être séparés.',
    posters: [
      { caption: 'La lumière de mon cœur · 3–5', alt: 'Affiche de la série La lumière de mon cœur' },
      { caption: 'Les histoires des prophètes · 6–8', alt: 'Affiche de Les histoires des prophètes' },
      { caption: 'Le voyage de la Sîra · 9–12', alt: 'Affiche de Le voyage de la Sîra' },
      { caption: 'Un conte et une leçon · Valeurs', alt: 'Affiche de Un conte et une leçon' },
      { caption: 'Les trésors du Coran · 6–8', alt: 'Affiche de Les trésors du Coran' },
      { caption: 'Mes invocations et mes bonnes manières · 3–5', alt: 'Affiche de Mes invocations et mes bonnes manières' },
    ],
  },

  languages: {
    kicker: 'Trois langues',
    heading: 'La langue ne s’arrête pas à l’interface',
    copy: 'Chez Majarra, la langue s’étend à la vidéo, aux histoires, à l’audio et au texte. Votre enfant peut lire dans une langue et écouter dans une autre, ou changer à tout moment sans perdre sa place.',
    textLang: 'Langue du texte',
    audioLang: 'Langue audio',
    hint: 'Lisez en arabe et écoutez en anglais, ou changez de langue à tout moment. Le réglage est enregistré par profil d’enfant et s’applique aux histoires, aux épisodes et à l’audio.',
    chips: ['Sous-titres écrits pour les épisodes', 'Doublage vocal des histoires', 'Interface complète RTL et LTR'],
    audioPrefix: 'Audio :',
    idleText: 'Appuyez pour écouter',
    source: 'Extrait de l’histoire « Dehors, dans la nature » · page 4 sur 22',
    narrationOf: (language: string) => `Narration en ${language}`,
  },

  devices: {
    kicker: 'Tous les appareils',
    heading: 'Commencez l’histoire sur la tablette, terminez-la sur la télévision',
    lead: 'La position de lecture et de visionnage suit l’enfant d’un appareil à l’autre, et la télévision devient une vue cinématique avec une navigation claire à la télécommande.',
    items: [
      { name: 'Android', note: 'Téléphone et tablette' },
      { name: 'iPhone et iPad', note: 'iOS et iPadOS' },
      { name: 'Android TV', note: 'Navigation complète à la télécommande' },
      { name: 'Apple TV', note: 'Plus tard' },
      { name: 'Smart TV', note: 'Là où c’est pris en charge' },
      { name: 'Web', note: 'app.majarra.app' },
    ],
    offlineStrong: 'Hors ligne :',
    offline: 'Téléchargez épisodes, histoires et jeux sur la formule Famille, et regardez en voiture ou en avion sans Internet. Les téléchargements restent sous le contrôle du parent.',
    storeNote: 'Télécharger l’application',
    qr: 'Pointez l’appareil photo de votre téléphone pour télécharger l’application Majarra',
    qrLabel: 'Code QR pour télécharger l’application Majarra',
    tvAlt: 'Le voyage des civilisations sur un écran de télévision',
    tabletAlt: 'Voyage à l’intérieur du corps sur une tablette',
    phoneAlt: 'Robo et les codes sur un téléphone',
    floatTitle: '3 épisodes téléchargés',
    floatText: 'Prêts à regarder sans Internet',
  },

  originals: {
    kicker: 'Originaux Majarra',
    heading: 'Des mondes que nous produisons nous-mêmes,',
    accent: 'pas seulement du contenu sous licence',
    copy: 'Séries, histoires, personnages et jeux créés par Majarra, reliés dans un même monde. L’enfant regarde l’épisode, lit son histoire, joue à son jeu, puis relève son défi.',
    heroTitle: 'Robo et les codes',
    heroAlt: 'Une scène cinématique de la série originale Robo et les codes',
    heroCopy: 'Une série originale sur la pensée logique et la programmation, avec le personnage « Robo » conçu au sein de Majarra, accompagnée d’une bande dessinée, d’un jeu de séquences et d’un projet de construction de circuits.',
    heroChips: ['9–12 ans', '2 saisons', 'Arabe · anglais', 'Original Majarra'],
    steps: [
      { title: 'Regarder la série', note: 'Des épisodes avec des personnages et un monde complet' },
      { title: 'Lire l’histoire', note: 'Une BD qui prolonge les événements de l’épisode' },
      { title: 'Jouer au jeu', note: 'Un jeu construit sur la compétence de la série' },
      { title: 'Relever le défi', note: 'Un projet pratique avec des étapes et un rapport' },
    ],
    cta: 'Tous les originaux Majarra',
  },

  start: {
    kicker: 'Trois étapes',
    heading: 'Comment commencer ?',
    copy: 'Deux minutes suffisent pour créer le compte famille et le premier profil d’enfant. Nous ne demandons pas de données dont nous n’avons pas besoin, et nous n’inscrivons pas l’enfant sous son nom complet.',
    steps: [
      {
        title: 'Créer le compte famille',
        copy: 'Un e-mail de parent et un code. Le compte appartient au parent, et tout ce qui concerne le paiement, les autorisations et la suppression reste sur son écran, pas dans la session de l’enfant.',
      },
      {
        title: 'Ajouter le profil, l’âge et les centres d’intérêt de votre enfant',
        copy: 'Un surnom, le mois et l’année de naissance, et quelques centres d’intérêt. Majarra choisit automatiquement la bonne tranche, et vous pouvez la modifier à tout moment.',
      },
      {
        title: 'Commencer un parcours personnel et sûr',
        copy: 'L’enfant ouvre son profil et ne trouve que des contenus pour son âge. Vous suivez depuis l’espace parents et réglez le temps d’écran, les téléchargements et les rapports.',
      },
    ],
    cta: 'Commencer maintenant',
  },

  plans: {
    kicker: 'Formules',
    heading: 'Choisissez celle qui convient à votre famille',
    copy: 'Le prix est visible dès la première étape et l’annulation est possible à tout moment. Nous ne cachons pas les différences entre les formules et nous ne demandons pas de carte pour commencer l’essai gratuit.',
    billingAria: 'Cycle de facturation',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    saveUpTo: 'Économisez jusqu’à 25 %',
    currencyLabel: 'Devise',
    perMonth: '/ mois',
    perYear: '/ an',
    freeAmount: 'Gratuit',
    freeNote: 'Pour toujours · sans carte',
    renewMonthly: 'Renouvellement mensuel · annulable à tout moment',
    renewYearlyWithSave: (percent: number) => `Renouvellement annuel · économisez ${percent} % · annulable à tout moment`,
    renewYearly: 'Renouvellement annuel · annulable à tout moment',
    compare: 'Tableau comparatif détaillé',
    compareHeaders: ['Fonctionnalité', 'Gratuit', 'Lite', 'Famille'],
    note: 'L’essai gratuit de la formule Famille est disponible sans carte et se termine automatiquement, sans frais, si vous ne continuez pas. Annulez depuis l’espace parents à tout moment ; l’abonnement court jusqu’à la fin de la période payée.',
    noteFine: 'Les prix affichés sont indicatifs avant le lancement et seront fixés dans la devise de votre pays à l’ouverture des abonnements.',
    flagBest: 'Le meilleur choix pour les familles',
    currencies: {
      SAR: 'Arabie saoudite · SAR',
      AED: 'Émirats arabes unis · AED',
      EGP: 'Égypte · EGP',
      USD: 'International · USD',
    },
    symbols: { SAR: 'SAR', AED: 'AED', EGP: 'EGP', USD: 'USD' },
    items: {
      free: {
        name: 'Gratuit',
        tagline: 'Essayez Majarra sans carte et sans engagement, et découvrez le contenu.',
        cta: 'Commencer gratuitement',
        features: [
          'Une bibliothèque limitée d’épisodes et d’histoires',
          'Des extraits de chaque planète',
          'Un profil d’enfant',
          'Pas de téléchargement hors ligne',
          'Pas de rapports détaillés',
        ],
      },
      lite: {
        name: 'Majarra Lite',
        tagline: 'Toute la bibliothèque principale en ligne, avec des publicités sûres et limitées.',
        cta: 'Choisir Lite',
        features: [
          'Toute la bibliothèque principale en ligne',
          'Publicités sûres, limitées et vérifiées manuellement',
          'Un profil d’enfant',
          'Rapports simplifiés',
          'Pas de téléchargement hors ligne',
        ],
      },
      family: {
        name: 'Majarra Famille',
        tagline: 'Tout Majarra sans publicité, pour plusieurs enfants et appareils, avec téléchargement hors ligne.',
        cta: 'Commencer l’essai gratuit',
        features: [
          'Aucune publicité',
          'Tous les contenus : épisodes, histoires, audio et jeux',
          'Téléchargement hors ligne des épisodes et des histoires',
          'Jusqu’à 5 profils d’enfants',
          'Jusqu’à 4 appareils, deux flux simultanés',
          'Rapports avancés par enfant',
          'Toutes les langues disponibles à l’écrit et à l’oral',
        ],
      },
    },
    compareRows: [
      { feature: 'Taille de la bibliothèque', free: 'Extraits', lite: 'Bibliothèque principale', family: 'Tous les contenus' },
      { feature: 'Publicités', free: 'Limitées', lite: 'Limitées et vérifiées', family: 'Aucune' },
      { feature: 'Profils d’enfants', free: '1', lite: '1', family: 'Jusqu’à 5' },
      { feature: 'Appareils liés', free: '1', lite: '2', family: 'Jusqu’à 4' },
      { feature: 'Flux simultanés', free: '1', lite: '1', family: '2' },
      { feature: 'Qualité vidéo', free: 'SD', lite: 'HD', family: 'Full HD' },
      { feature: 'Téléchargement hors ligne', free: 'Non', lite: 'Non', family: 'Oui' },
      { feature: 'Albums illustrés et BD', free: 'Extraits', lite: 'Oui', family: 'Oui' },
      { feature: 'Histoires audio', free: 'Extraits', lite: 'Oui', family: 'Oui' },
      { feature: 'Jeux et projets', free: 'Extraits', lite: 'Partiel', family: 'Complet' },
      { feature: 'Rapports parentaux', free: 'Non', lite: 'Simplifiés', family: 'Avancés' },
      { feature: 'Limites de temps d’écran', free: 'Oui', lite: 'Oui', family: 'Oui' },
      { feature: 'Langues du texte et de l’audio', free: 'Arabe', lite: 'Arabe + une', family: 'Les trois' },
      { feature: 'Prise en charge de la TV', free: 'Non', lite: 'Oui', family: 'Oui' },
    ],
  },

  reviews: {
    kicker: 'Confiance',
    heading: 'Comment nous révisons les contenus avant que votre enfant les voie',
    copy: 'Nous n’avons pas encore lancé publiquement : nous n’affichons donc ni notes ni nombre d’utilisateurs. Nous montrons plutôt notre processus de révision, et des retours documentés du programme de test anticipé.',
    method: [
      {
        title: '1 · Révision pédagogique',
        copy: 'Un spécialiste de l’éducation de la petite enfance examine l’objectif d’apprentissage, l’adéquation à l’âge et le niveau de langue avant la production.',
      },
      {
        title: '2 · Révision de sécurité',
        copy: 'Les scènes, l’audio et les effets sont vérifiés : pas de scènes effrayantes, pas de clignotements rapides, et aucun lien externe dans l’expérience de l’enfant.',
      },
      {
        title: '3 · Révision spécialisée des contenus religieux',
        copy: 'Les contenus religieux passent par un réviseur spécialisé, et leurs sources sont citées sur la page du titre concerné.',
      },
    ],
    items: [
      {
        tag: 'Programme de test anticipé',
        quote: '« La première fois que mon fils s’est assis et a lu tout seul. “Lis avec moi” lui a fait suivre la phrase des yeux au lieu d’attendre l’audio. »',
        name: 'Mère de deux enfants',
        note: 'Riyad · 5 et 8 ans',
      },
      {
        tag: 'Programme de test anticipé',
        quote: '« C’est le rapport hebdomadaire qui a fait la différence. Pas un décompte d’heures, mais quelle compétence a vraiment besoin d’être revue. »',
        name: 'Père de trois enfants',
        note: 'Le Caire · 4, 7 et 10 ans',
      },
      {
        tag: 'Révision pédagogique',
        quote: '« Relier l’épisode à une histoire, puis à un jeu, puis à une activité à la maison ancre l’idée bien mieux que de revoir le même contenu. »',
        name: 'Réviseuse pédagogique',
        note: 'Spécialiste de l’éducation de la petite enfance',
      },
    ],
    honesty:
      'Nous n’utilisons aucune note ni témoignage inventé, et nous n’affichons aucun chiffre du type « un million d’utilisateurs » ou « des milliers d’histoires » avant qu’il ne soit réel et vérifiable. Les citations ci-dessus proviennent de familles ayant participé aux tests anticipés, avec leur accord et sous des noms abrégés pour protéger leur vie privée.',
  },

  faq: {
    kicker: 'FAQ',
    heading: 'Les questions que les parents posent avant de s’abonner',
    helpCta: 'Centre d’aide et toutes les questions',
    items: [
      {
        q: 'À quels âges s’adresse la plateforme ?',
        a: 'De 3 à 12 ans, en trois parcours : 3–5, 6–8 et 9–12. L’interface, le niveau de lecture, la durée des sessions et les types de jeux changent avec chaque parcours, et la progression est conservée quand l’enfant passe d’une étape à la suivante.',
      },
      {
        q: 'Peut-on utiliser l’application gratuitement ?',
        a: 'Oui. La formule gratuite est permanente et donne accès à une bibliothèque limitée, à des extraits de chaque planète et à un profil d’enfant, sans carte bancaire. La formule Famille dispose d’un essai gratuit distinct qui se termine automatiquement sans frais.',
      },
      {
        q: 'Le contenu est-il sûr ?',
        a: 'Chaque titre passe une révision pédagogique et une révision de sécurité avant publication : pas de scènes effrayantes, pas de clignotements rapides, et aucun lien externe dans la session de l’enfant. Les achats, les autorisations et la suppression se font uniquement sur l’écran du parent.',
      },
      {
        q: 'Quelles langues sont disponibles ?',
        a: 'L’arabe, l’anglais et le français. La langue s’étend à l’interface, à la vidéo, aux histoires et à l’audio, et la langue du texte et la langue audio peuvent être choisies indépendamment pour chaque profil d’enfant.',
      },
      {
        q: 'Est-ce que ça fonctionne hors ligne ?',
        a: 'Oui sur la formule Famille : téléchargez des épisodes, des histoires et certains jeux pour regarder et lire sans Internet. Les téléchargements sont sous le contrôle du parent et peuvent être limités ou bloqués par profil d’enfant.',
      },
      {
        q: 'Combien d’appareils ?',
        a: 'La formule Gratuite autorise un appareil, Lite deux, et Famille jusqu’à quatre appareils avec deux flux simultanés. La gestion et la suppression des appareils se font depuis l’espace parents.',
      },
      {
        q: 'Puis-je créer un profil pour chaque enfant ?',
        a: 'Oui, jusqu’à cinq profils sur la formule Famille. Chaque profil a son parcours d’âge, ses recommandations, sa progression, ses favoris et ses rapports, et les résultats d’âges différents ne sont jamais fusionnés en un seul score.',
      },
      {
        q: 'Quelle est la différence entre Lite et Famille ?',
        a: 'Lite donne la bibliothèque principale en ligne pour un enfant, avec des publicités limitées et des rapports simplifiés. Famille est sans publicité, avec tous les contenus y compris histoires, audio et jeux, plus le téléchargement hors ligne, plusieurs profils et appareils, et des rapports avancés.',
      },
      {
        q: 'Y a-t-il des publicités ?',
        a: 'Sur les formules Gratuite et Lite, il y a des publicités limitées et vérifiées manuellement, qui ne ciblent pas l’enfant selon son comportement et ne le font pas sortir de l’application. La formule Famille est totalement sans publicité.',
      },
      {
        q: 'Comment fonctionnent les rapports parentaux ?',
        a: 'Un rapport hebdomadaire par enfant indique ce qu’il a regardé, lu et joué, les compétences maîtrisées et celles à revoir, ainsi que la progression en lecture. Il est rédigé simplement, sans jargon, et n’affiche aucun classement ni comparaison avec d’autres enfants.',
      },
      {
        q: 'Comment les contenus religieux sont-ils choisis ?',
        a: 'Ils passent par un réviseur spécialisé avant publication, et leurs sources sont citées sur la page du titre. Ils apparaissent comme une catégorie de Majarra comme les autres mondes, et ne servent jamais à mesurer la religiosité d’un enfant ni à afficher un quelconque « score de foi ».',
      },
      {
        q: 'Puis-je annuler l’abonnement ?',
        a: 'Oui, depuis l’espace parents à tout moment, en deux étapes, sans appel ni message. Votre accès continue jusqu’à la fin de la période payée et aucun renouvellement n’est ensuite prélevé.',
      },
      {
        q: 'Est-ce que ça fonctionne sur la télévision ?',
        a: 'Oui sur Android TV, avec une navigation complète à la télécommande, un texte plus grand et des rangées horizontales adaptées à la distance de visionnage. Apple TV arrive plus tard, et Smart TV là où c’est pris en charge. L’appairage se fait par code QR ou par un code court depuis l’écran du parent.',
      },
      {
        q: 'Peut-on changer l’âge ou le niveau de lecture ?',
        a: 'Oui. Vous pouvez ajuster la date de naissance ou relever le niveau de lecture manuellement si votre enfant est en avance, ou l’abaisser pour une expérience plus calme. Le changement s’applique immédiatement aux recommandations et conserve la progression déjà acquise.',
      },
    ],
  },

  download: {
    heading: 'Commencez dès aujourd’hui le voyage de votre enfant dans Majarra',
    copy: 'Créez gratuitement le compte famille, ajoutez le profil de votre enfant, et laissez-le explorer un monde sûr d’histoires et de savoir.',
    ctaPrimary: 'Commencer l’essai gratuit',
    ctaSecondary: 'Télécharger l’application',
    fine: 'Sans carte bancaire · annulable à tout moment · disponible sur téléphone, tablette, télévision et web',
  },

  partners: {
    kicker: 'Partenariats',
    heading: 'Travailler avec Majarra',
    accent: 'écoles, crèches et créateurs de contenu',
    copy: 'Nous travaillons avec des écoles, des crèches, des éditeurs, des producteurs de contenu et des comédiens voix. Laissez vos coordonnées et nous vous répondrons avec des prochaines étapes claires.',
    audiences: [
      {
        title: 'Écoles et maternelles',
        copy: 'Comptes de classe, contenus reliés aux programmes, et rapports pour les enseignants plutôt que pour les familles.',
      },
      {
        title: 'Crèches et centres',
        copy: 'Licences pour le visionnage collectif en classe, et contenus courts adaptés au temps de regroupement.',
      },
      {
        title: 'Éditeurs et producteurs',
        copy: 'Concédez vos œuvres sous licence dans Majarra, ou produisez avec nous une série originale selon notre cahier des charges pédagogique.',
      },
      {
        title: 'Comédiens voix et créateurs',
        copy: 'Enregistrement vocal en arabe standard, en anglais ou en français, ainsi qu’illustration et animation.',
      },
    ],
    form: {
      heading: 'Demander une collaboration',
      lead: 'Nous répondons généralement sous deux jours ouvrés. Nous ne partageons vos coordonnées avec personne.',
      type: 'Type d’organisation',
      types: {
        school: 'École',
        nursery: 'Crèche ou maternelle',
        publisher: 'Éditeur',
        producer: 'Producteur de contenu',
        creator: 'Comédien voix ou créateur',
        other: 'Autre',
      },
      name: 'Nom',
      namePlaceholder: 'Votre nom complet',
      organization: 'Nom de l’organisation',
      organizationPlaceholder: 'Nom de l’école ou de l’entreprise',
      email: 'E-mail',
      emailPlaceholder: 'nom@exemple.com',
      phone: 'Téléphone',
      optional: 'facultatif',
      phonePlaceholder: '+33 6 00 00 00 00',
      country: 'Pays',
      countryPlaceholder: 'France, Maroc, Égypte…',
      message: 'Détails de la collaboration',
      messagePlaceholder:
        'Décrivez brièvement la collaboration envisagée, ainsi que le nombre d’enfants ou le volume de contenu si c’est pertinent.',
      submit: 'Envoyer la demande',
      submitting: 'Envoi…',
      successTitle: 'Nous avons reçu votre demande',
      successBody:
        'Nous allons l’examiner et répondre à votre e-mail sous deux jours ouvrés. Vous pouvez envoyer une autre demande si besoin.',
      sendAnother: 'Envoyer une autre demande',
      errorGeneric: 'Impossible d’envoyer la demande. Réessayez dans un instant.',
      errorEmail: 'Saisissez une adresse e-mail valide.',
      errorRequired: 'Veuillez d’abord compléter les champs obligatoires.',
      errorRate: 'Trop de demandes. Attendez une minute et réessayez.',
      privacy: 'En utilisant ce formulaire, vous acceptez que nous vous contactions uniquement au sujet de votre demande.',
    },
  },

  footer: {
    about:
      'Une plateforme sûre, pensée d’abord pour l’arabe, pour les enfants de 3 à 12 ans, qui réunit regarder, lire, écouter, jouer et apprendre dans une seule expérience, avec de vrais outils pour les parents.',
    columns: {
      majarra: {
        title: 'Majarra',
        links: ['À propos de Majarra', 'Notre mission', 'Équipe de révision', 'Carrières', 'Nous contacter'],
      },
      discover: {
        title: 'Découvrir',
        links: ['Planètes', 'Séries', 'Histoires', 'Jeux', 'Contenus audio', 'Originaux Majarra'],
      },
      parents: {
        title: 'Pour les parents',
        links: ['Sécurité', 'Apprentissage', 'Contrôle parental', 'Formules', 'Appareils', 'Centre d’aide'],
      },
      partners: {
        title: 'Partenariats',
        links: ['Producteurs de contenu', 'Éditeurs', 'Écoles', 'Comédiens voix et créateurs', 'Parrainages'],
      },
      legal: {
        title: 'Mentions légales',
        links: [
          'Confidentialité',
          'Confidentialité des enfants',
          'Conditions d’utilisation',
          'Politique relative aux cookies',
          'Politique publicitaire',
          'Demande de suppression de compte',
          'Droits sur les contenus',
        ],
      },
    },
    langLabel: 'Langue',
    stores: 'Boutiques d’applications',
    social: ['Majarra sur YouTube', 'Majarra sur Instagram', 'Majarra sur X', 'Majarra sur TikTok'],
    rights: 'Tous droits réservés',
  },
}
