-- 0013 — qisas story pages.
--
-- CORRECTED 2026-08-08. The original content of this migration was unusable and is
-- deliberately not carried forward.
--
-- It inserted 80 `story_pages` rows plus their localizations, but every `story_id` it
-- referenced was a BOOK id (`book-qisas-p1` … `book-qisas-j5`) created by 0012.
-- `story_pages.story_id` is a foreign key to `stories(id)`, and none of those ids is a
-- story, so every one of the 80 rows would have been an orphan pointing at a row that
-- does not exist in the referenced table. Verified against the database: zero rows in
-- `stories` match `book-qisas-%`. It also carried no real page text — the pages were
-- structural placeholders with `image_asset_id` NULL.
--
-- The qisas page content now exists properly: 186 `story_pages` rows, each with Arabic
-- body text in `story_page_localizations`, its narrative role, layout and motion value,
-- loaded from the authored sources under docs/content/planets/05-qisas/. That set is
-- correctly parented to real `stories` rows.
--
-- This migration is intentionally left as a no-op so the chain stays numbered and
-- 0014-0017 can apply. Removing the file would break `d1_migrations` ordering for any
-- environment that has already recorded it.

SELECT 'migration 0013 intentionally applies no data - see the comment above' AS note;
