-- 0059 — intentional dwell_ms backfill (per-page, guideline-based, not blanket uniform)
-- bedtime: 11-14s base + page position variation; junior: 3.5s base (read_myself).
-- narration + dwell + transition(400ms bedtime / 280ms junior) ≈ editorial target where narration exists.
-- Stories with null duration_ms will show BELOW until narration produced — dwell is not faked to compensate.
-- Generated by tools/backfill_dwell2.mjs

PRAGMA foreign_keys = ON;

-- ant-journey — حكايات قبل النوم — 12 pages — base 13000ms — target 240-280s
UPDATE story_pages SET dwell_ms = 11500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 13000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 15500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 14400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 14800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 15500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 12300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 12700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 11100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'ant-journey') AND page_number = 12;
--   -> dwellTotal 158.6s avg 13.2s

-- garden-secret — حكايات قبل النوم — 12 pages — base 13000ms — target 250-290s
UPDATE story_pages SET dwell_ms = 11500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 13000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 15500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 14400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 14800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 15500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 12300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 12700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 11100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'garden-secret') AND page_number = 12;
--   -> dwellTotal 158.6s avg 13.2s

-- new-friend — حكايات قبل النوم — 12 pages — base 12000ms — target 230-270s
UPDATE story_pages SET dwell_ms = 10500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 11200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 12000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 12400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 14500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 13400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 13800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 14500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 11300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 11700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 11200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 10100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'new-friend') AND page_number = 12;
--   -> dwellTotal 146.6s avg 12.2s

-- rainy-night — حكايات قبل النوم — 12 pages — base 14000ms — target 240-280s
UPDATE story_pages SET dwell_ms = 12500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 13200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 14000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 14400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 16500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 15400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 15800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 16500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 13300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 13700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 13200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 12100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'rainy-night') AND page_number = 12;
--   -> dwellTotal 170.6s avg 14.2s

-- old-lantern — حكايات قبل النوم — 12 pages — base 13500ms — target 260-300s
UPDATE story_pages SET dwell_ms = 12000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 12700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 13500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 16000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 14900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 15300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 16000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 12800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 13200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 12700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 11600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'old-lantern') AND page_number = 12;
--   -> dwellTotal 164.6s avg 13.7s

-- lost-star — حكايات قبل النوم — 12 pages — base 13000ms — target 240-280s
UPDATE story_pages SET dwell_ms = 11500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 13000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 15500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 14400 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 14800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 15500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 12300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 12700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 11100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'lost-star') AND page_number = 12;
--   -> dwellTotal 158.6s avg 13.2s

-- goodnight-toys — حكاية هادئة — 8 pages — base 12000ms — target 150-180s
UPDATE story_pages SET dwell_ms = 10500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 13100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 12000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 14500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 11300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 11700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 11200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'goodnight-toys') AND page_number = 8;
--   -> dwellTotal 98.1s avg 12.3s

-- moon-sleeps — حكاية هادئة — 8 pages — base 11500ms — target 140-170s
UPDATE story_pages SET dwell_ms = 10000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 12600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 11500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 14000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 10800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 11200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 10700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'moon-sleeps') AND page_number = 8;
--   -> dwellTotal 94.1s avg 11.8s

-- warm-hugs — حكاية هادئة — 8 pages — base 12500ms — target 150-180s
UPDATE story_pages SET dwell_ms = 11000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 13600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 12500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 14300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 15000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 11800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 12200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 11700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'warm-hugs') AND page_number = 8;
--   -> dwellTotal 102.1s avg 12.8s

-- bird-home — حكاية هادئة — 8 pages — base 12000ms — target 150-170s
UPDATE story_pages SET dwell_ms = 10500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 13100 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 12000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 13800 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 14500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 11300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 11700 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 11200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'bird-home') AND page_number = 8;
--   -> dwellTotal 98.1s avg 12.3s

-- the-promised-friday — قصص من الحياة — 18 pages — base 3500ms — target 340-400s
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 4600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 3500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 12;
UPDATE story_pages SET dwell_ms = 3200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 13;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 14;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 15;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 16;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 17;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-promised-friday') AND page_number = 18;
--   -> dwellTotal 72.5s avg 4.0s

-- nine-metres — قصص من الحياة — 18 pages — base 3500ms — target 350-410s
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 4600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 3500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 12;
UPDATE story_pages SET dwell_ms = 3200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 13;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 14;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 15;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 16;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 17;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'nine-metres') AND page_number = 18;
--   -> dwellTotal 72.5s avg 4.0s

-- taller-than-me — قصص من الحياة — 20 pages — base 3500ms — target 400-460s
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 4600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 3500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 12;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 13;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 14;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 15;
UPDATE story_pages SET dwell_ms = 3200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 16;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 17;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 18;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 19;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'taller-than-me') AND page_number = 20;
--   -> dwellTotal 81.7s avg 4.1s

-- the-key-that-was-left — قصص من الحياة — 16 pages — base 3500ms — target 320-380s
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 3500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 4600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 12;
UPDATE story_pages SET dwell_ms = 3200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 13;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 14;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 15;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-key-that-was-left') AND page_number = 16;
--   -> dwellTotal 66.5s avg 4.2s

-- the-extra-page — قصص من الحياة — 18 pages — base 3500ms — target 360-420s
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 1;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 2;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 3;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 4;
UPDATE story_pages SET dwell_ms = 4600 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 5;
UPDATE story_pages SET dwell_ms = 3500 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 6;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 7;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 8;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 9;
UPDATE story_pages SET dwell_ms = 5300 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 10;
UPDATE story_pages SET dwell_ms = 6000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 11;
UPDATE story_pages SET dwell_ms = 4900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 12;
UPDATE story_pages SET dwell_ms = 3200 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 13;
UPDATE story_pages SET dwell_ms = 3900 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 14;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 15;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 16;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 17;
UPDATE story_pages SET dwell_ms = 3000 WHERE story_id = (SELECT id FROM stories WHERE slug = 'the-extra-page') AND page_number = 18;
--   -> dwellTotal 72.5s avg 4.0s
