-- 0067 Complete Drawing 50 — paired reference_full + challenge per activity
-- R2: complete-drawing/{id}/reference_full.png , challenge.png , thumbnail.jpg  in THUMBS_BUCKET
-- D1: category='complete', r2_key = challenge, thumb_r2_key = thumbnail, extra_json holds reference_full key
-- All 50 seeded as status='ready' for instant play; admin can toggle to published

INSERT OR IGNORE INTO creative_drawings (id, category, title_ar, title_en, age_min, age_max, difficulty, r2_key, thumb_r2_key, extra_json, status, is_featured, is_new, sort_order, tags, asset_id) VALUES
-- Animals 01-10
('complete-butterfly-01','complete','الفراشة','Butterfly',4,5,'سهل','complete-drawing/butterfly-01/challenge.png','complete-drawing/butterfly-01/thumbnail.jpg','{"reference_full":"complete-drawing/butterfly-01/reference_full.png","group":"animals","tag":"تناظر"}','ready',1,1,1,'حيوانات,تناظر,سهل','complete-butterfly-01'),
('complete-bird-01','complete','عصفور','Bird',4,5,'سهل','complete-drawing/bird-01/challenge.png','complete-drawing/bird-01/thumbnail.jpg','{"reference_full":"complete-drawing/bird-01/reference_full.png","group":"animals","tag":"أكمل الجسم"}','ready',1,1,2,'حيوانات,سهل','complete-bird-01'),
('complete-cat-01','complete','قطة','Cat',4,5,'سهل','complete-drawing/cat-01/challenge.png','complete-drawing/cat-01/thumbnail.jpg','{"reference_full":"complete-drawing/cat-01/reference_full.png","group":"animals","tag":"تناظر"}','ready',1,1,3,'حيوانات,تناظر,سهل','complete-cat-01'),
('complete-fish-01','complete','سمكة','Fish',4,5,'سهل','complete-drawing/fish-01/challenge.png','complete-drawing/fish-01/thumbnail.jpg','{"reference_full":"complete-drawing/fish-01/reference_full.png","group":"animals"}','ready',0,1,4,'حيوانات,سهل','complete-fish-01'),
('complete-rabbit-01','complete','أرنب','Rabbit',4,5,'سهل','complete-drawing/rabbit-01/challenge.png','complete-drawing/rabbit-01/thumbnail.jpg','{"reference_full":"complete-drawing/rabbit-01/reference_full.png","group":"animals"}','ready',0,1,5,'حيوانات,سهل','complete-rabbit-01'),
('complete-panda-01','complete','باندا','Panda',4,5,'سهل','complete-drawing/panda-01/challenge.png','complete-drawing/panda-01/thumbnail.jpg','{"reference_full":"complete-drawing/panda-01/reference_full.png","group":"animals"}','ready',0,1,6,'حيوانات,سهل','complete-panda-01'),
('complete-lion-01','complete','أسد صغير','Baby Lion',5,7,'متوسط','complete-drawing/lion-01/challenge.png','complete-drawing/lion-01/thumbnail.jpg','{"reference_full":"complete-drawing/lion-01/reference_full.png","group":"animals"}','ready',0,1,7,'حيوانات,متوسط','complete-lion-01'),
('complete-giraffe-01','complete','زرافة','Giraffe',5,7,'متوسط','complete-drawing/giraffe-01/challenge.png','complete-drawing/giraffe-01/thumbnail.jpg','{"reference_full":"complete-drawing/giraffe-01/reference_full.png","group":"animals"}','ready',0,1,8,'حيوانات,متوسط','complete-giraffe-01'),
('complete-turtle-01','complete','سلحفاة','Turtle',5,7,'متوسط','complete-drawing/turtle-01/challenge.png','complete-drawing/turtle-01/thumbnail.jpg','{"reference_full":"complete-drawing/turtle-01/reference_full.png","group":"animals"}','ready',0,1,9,'حيوانات,متوسط','complete-turtle-01'),
('complete-dino-01','complete','ديناصور','Dino',5,7,'متوسط','complete-drawing/dino-01/challenge.png','complete-drawing/dino-01/thumbnail.jpg','{"reference_full":"complete-drawing/dino-01/reference_full.png","group":"animals"}','ready',0,1,10,'حيوانات,متوسط','complete-dino-01'),
-- Space 11-18
('complete-rocket-01','complete','صاروخ','Rocket',4,5,'سهل','complete-drawing/rocket-01/challenge.png','complete-drawing/rocket-01/thumbnail.jpg','{"reference_full":"complete-drawing/rocket-01/reference_full.png","group":"space","tag":"تناظر"}','ready',1,1,11,'فضاء,تناظر,سهل','complete-rocket-01'),
('complete-planet-ring-01','complete','كوكب بحلقات','Ring Planet',4,5,'سهل','complete-drawing/planet-ring-01/challenge.png','complete-drawing/planet-ring-01/thumbnail.jpg','{"reference_full":"complete-drawing/planet-ring-01/reference_full.png","group":"space"}','ready',0,1,12,'فضاء,سهل','complete-planet-ring-01'),
('complete-moon-star-01','complete','قمر ونجمة','Moon Star',4,5,'سهل','complete-drawing/moon-star-01/challenge.png','complete-drawing/moon-star-01/thumbnail.jpg','{"reference_full":"complete-drawing/moon-star-01/reference_full.png","group":"space"}','ready',0,1,13,'فضاء,سهل','complete-moon-star-01'),
('complete-ufo-01','complete','مركبة فضائية','UFO',5,7,'متوسط','complete-drawing/ufo-01/challenge.png','complete-drawing/ufo-01/thumbnail.jpg','{"reference_full":"complete-drawing/ufo-01/reference_full.png","group":"space","tag":"تناظر"}','ready',0,1,14,'فضاء,تناظر,متوسط','complete-ufo-01'),
('complete-astronaut-01','complete','رائد فضاء','Astronaut',5,7,'متوسط','complete-drawing/astronaut-01/challenge.png','complete-drawing/astronaut-01/thumbnail.jpg','{"reference_full":"complete-drawing/astronaut-01/reference_full.png","group":"space"}','ready',0,1,15,'فضاء,متوسط','complete-astronaut-01'),
('complete-rover-01','complete','مركبة قمرية','Rover',5,7,'متوسط','complete-drawing/rover-01/challenge.png','complete-drawing/rover-01/thumbnail.jpg','{"reference_full":"complete-drawing/rover-01/reference_full.png","group":"space"}','ready',0,1,16,'فضاء,متوسط','complete-rover-01'),
('complete-station-01','complete','محطة فضائية','Station',7,9,'مفصل','complete-drawing/station-01/challenge.png','complete-drawing/station-01/thumbnail.jpg','{"reference_full":"complete-drawing/station-01/reference_full.png","group":"space"}','ready',0,1,17,'فضاء,صعب','complete-station-01'),
('complete-alien-planet-01','complete','كوكب خيالي','Alien Planet',7,9,'مفصل','complete-drawing/alien-planet-01/challenge.png','complete-drawing/alien-planet-01/thumbnail.jpg','{"reference_full":"complete-drawing/alien-planet-01/reference_full.png","group":"space"}','ready',0,1,18,'فضاء,صعب','complete-alien-planet-01'),
-- Nature 19-26
('complete-flower-01','complete','زهرة','Flower',4,5,'سهل','complete-drawing/flower-01/challenge.png','complete-drawing/flower-01/thumbnail.jpg','{"reference_full":"complete-drawing/flower-01/reference_full.png","group":"nature","tag":"تناظر"}','ready',1,1,19,'طبيعة,تناظر,سهل','complete-flower-01'),
('complete-tree-01','complete','شجرة','Tree',4,5,'سهل','complete-drawing/tree-01/challenge.png','complete-drawing/tree-01/thumbnail.jpg','{"reference_full":"complete-drawing/tree-01/reference_full.png","group":"nature"}','ready',0,1,20,'طبيعة,سهل','complete-tree-01'),
('complete-rainbow-01','complete','قوس قزح','Rainbow',4,5,'سهل','complete-drawing/rainbow-01/challenge.png','complete-drawing/rainbow-01/thumbnail.jpg','{"reference_full":"complete-drawing/rainbow-01/reference_full.png","group":"nature"}','ready',0,1,21,'طبيعة,سهل','complete-rainbow-01'),
('complete-sun-cloud-01','complete','شمس وسحابة','Sun Cloud',4,5,'سهل','complete-drawing/sun-cloud-01/challenge.png','complete-drawing/sun-cloud-01/thumbnail.jpg','{"reference_full":"complete-drawing/sun-cloud-01/reference_full.png","group":"nature"}','ready',0,1,22,'طبيعة,سهل','complete-sun-cloud-01'),
('complete-palm-01','complete','نخلة','Palm',5,7,'متوسط','complete-drawing/palm-01/challenge.png','complete-drawing/palm-01/thumbnail.jpg','{"reference_full":"complete-drawing/palm-01/reference_full.png","group":"nature"}','ready',0,1,23,'طبيعة,متوسط','complete-palm-01'),
('complete-mountain-01','complete','منظر جبلي','Mountain',5,7,'متوسط','complete-drawing/mountain-01/challenge.png','complete-drawing/mountain-01/thumbnail.jpg','{"reference_full":"complete-drawing/mountain-01/reference_full.png","group":"nature"}','ready',0,1,24,'طبيعة,متوسط','complete-mountain-01'),
('complete-waterfall-01','complete','شلال','Waterfall',7,9,'مفصل','complete-drawing/waterfall-01/challenge.png','complete-drawing/waterfall-01/thumbnail.jpg','{"reference_full":"complete-drawing/waterfall-01/reference_full.png","group":"nature"}','ready',0,1,25,'طبيعة,صعب','complete-waterfall-01'),
('complete-garden-01','complete','حديقة','Garden',7,9,'مفصل','complete-drawing/garden-01/challenge.png','complete-drawing/garden-01/thumbnail.jpg','{"reference_full":"complete-drawing/garden-01/reference_full.png","group":"nature"}','ready',0,1,26,'طبيعة,صعب','complete-garden-01'),
-- Vehicles 27-34
('complete-car-01','complete','سيارة','Car',4,5,'سهل','complete-drawing/car-01/challenge.png','complete-drawing/car-01/thumbnail.jpg','{"reference_full":"complete-drawing/car-01/reference_full.png","group":"vehicles"}','ready',1,1,27,'مركبات,سهل','complete-car-01'),
('complete-sailboat-01','complete','قارب شراعي','Sailboat',4,5,'سهل','complete-drawing/sailboat-01/challenge.png','complete-drawing/sailboat-01/thumbnail.jpg','{"reference_full":"complete-drawing/sailboat-01/reference_full.png","group":"vehicles"}','ready',0,1,28,'مركبات,سهل','complete-sailboat-01'),
('complete-balloon-01','complete','منطاد','Balloon',4,5,'سهل','complete-drawing/balloon-01/challenge.png','complete-drawing/balloon-01/thumbnail.jpg','{"reference_full":"complete-drawing/balloon-01/reference_full.png","group":"vehicles","tag":"تناظر"}','ready',0,1,29,'مركبات,تناظر,سهل','complete-balloon-01'),
('complete-plane-01','complete','طائرة','Plane',5,7,'متوسط','complete-drawing/plane-01/challenge.png','complete-drawing/plane-01/thumbnail.jpg','{"reference_full":"complete-drawing/plane-01/reference_full.png","group":"vehicles"}','ready',0,1,30,'مركبات,متوسط','complete-plane-01'),
('complete-train-01','complete','قطار','Train',5,7,'متوسط','complete-drawing/train-01/challenge.png','complete-drawing/train-01/thumbnail.jpg','{"reference_full":"complete-drawing/train-01/reference_full.png","group":"vehicles"}','ready',0,1,31,'مركبات,متوسط','complete-train-01'),
('complete-firetruck-01','complete','شاحنة إطفاء','Firetruck',5,7,'متوسط','complete-drawing/firetruck-01/challenge.png','complete-drawing/firetruck-01/thumbnail.jpg','{"reference_full":"complete-drawing/firetruck-01/reference_full.png","group":"vehicles"}','ready',0,1,32,'مركبات,متوسط','complete-firetruck-01'),
('complete-excavator-01','complete','حفار','Excavator',7,9,'مفصل','complete-drawing/excavator-01/challenge.png','complete-drawing/excavator-01/thumbnail.jpg','{"reference_full":"complete-drawing/excavator-01/reference_full.png","group":"vehicles"}','ready',0,1,33,'مركبات,صعب','complete-excavator-01'),
('complete-submarine-01','complete','غواصة','Submarine',7,9,'مفصل','complete-drawing/submarine-01/challenge.png','complete-drawing/submarine-01/thumbnail.jpg','{"reference_full":"complete-drawing/submarine-01/reference_full.png","group":"vehicles"}','ready',0,1,34,'مركبات,صعب','complete-submarine-01'),
-- Home 35-41
('complete-house-01','complete','بيت صغير','Small House',4,5,'سهل','complete-drawing/house-01/challenge.png','complete-drawing/house-01/thumbnail.jpg','{"reference_full":"complete-drawing/house-01/reference_full.png","group":"home","tag":"تناظر"}','ready',1,1,35,'البيت,تناظر,سهل','complete-house-01'),
('complete-cupcake-01','complete','كوب كيك','Cupcake',4,5,'سهل','complete-drawing/cupcake-01/challenge.png','complete-drawing/cupcake-01/thumbnail.jpg','{"reference_full":"complete-drawing/cupcake-01/reference_full.png","group":"home"}','ready',0,1,36,'البيت,سهل','complete-cupcake-01'),
('complete-teddy-01','complete','دبدوب','Teddy',4,5,'سهل','complete-drawing/teddy-01/challenge.png','complete-drawing/teddy-01/thumbnail.jpg','{"reference_full":"complete-drawing/teddy-01/reference_full.png","group":"home","tag":"تناظر"}','ready',0,1,37,'البيت,تناظر,سهل','complete-teddy-01'),
('complete-backpack-01','complete','حقيبة مدرسية','Backpack',4,5,'سهل','complete-drawing/backpack-01/challenge.png','complete-drawing/backpack-01/thumbnail.jpg','{"reference_full":"complete-drawing/backpack-01/reference_full.png","group":"home"}','ready',0,1,38,'البيت,سهل','complete-backpack-01'),
('complete-art-table-01','complete','طاولة رسم','Art Table',5,7,'متوسط','complete-drawing/art-table-01/challenge.png','complete-drawing/art-table-01/thumbnail.jpg','{"reference_full":"complete-drawing/art-table-01/reference_full.png","group":"home"}','ready',0,1,39,'البيت,متوسط','complete-art-table-01'),
('complete-kids-room-01','complete','غرفة طفل','Kids Room',7,9,'مفصل','complete-drawing/kids-room-01/challenge.png','complete-drawing/kids-room-01/thumbnail.jpg','{"reference_full":"complete-drawing/kids-room-01/reference_full.png","group":"home"}','ready',0,1,40,'البيت,صعب','complete-kids-room-01'),
('complete-playground-01','complete','ملعب','Playground',7,9,'مفصل','complete-drawing/playground-01/challenge.png','complete-drawing/playground-01/thumbnail.jpg','{"reference_full":"complete-drawing/playground-01/reference_full.png","group":"home"}','ready',0,1,41,'البيت,صعب','complete-playground-01'),
-- Food 42-45
('complete-apple-01','complete','تفاحة','Apple',4,5,'سهل','complete-drawing/apple-01/challenge.png','complete-drawing/apple-01/thumbnail.jpg','{"reference_full":"complete-drawing/apple-01/reference_full.png","group":"food","tag":"تناظر"}','ready',1,1,42,'طعام,تناظر,سهل','complete-apple-01'),
('complete-icecream-01','complete','آيس كريم','Ice Cream',4,5,'سهل','complete-drawing/icecream-01/challenge.png','complete-drawing/icecream-01/thumbnail.jpg','{"reference_full":"complete-drawing/icecream-01/reference_full.png","group":"food"}','ready',0,1,43,'طعام,سهل','complete-icecream-01'),
('complete-fruit-basket-01','complete','سلة فاكهة','Fruit Basket',5,7,'متوسط','complete-drawing/fruit-basket-01/challenge.png','complete-drawing/fruit-basket-01/thumbnail.jpg','{"reference_full":"complete-drawing/fruit-basket-01/reference_full.png","group":"food"}','ready',0,1,44,'طعام,متوسط','complete-fruit-basket-01'),
('complete-pizza-01','complete','بيتزا','Pizza',5,7,'متوسط','complete-drawing/pizza-01/challenge.png','complete-drawing/pizza-01/thumbnail.jpg','{"reference_full":"complete-drawing/pizza-01/reference_full.png","group":"food"}','ready',0,1,45,'طعام,متوسط','complete-pizza-01'),
-- Fantasy 46-50
('complete-unicorn-01','complete','وحيد القرن','Unicorn',5,7,'متوسط','complete-drawing/unicorn-01/challenge.png','complete-drawing/unicorn-01/thumbnail.jpg','{"reference_full":"complete-drawing/unicorn-01/reference_full.png","group":"fantasy"}','ready',0,1,46,'خيال,متوسط','complete-unicorn-01'),
('complete-dragon-01','complete','تنين صغير','Baby Dragon',5,7,'متوسط','complete-drawing/dragon-01/challenge.png','complete-drawing/dragon-01/thumbnail.jpg','{"reference_full":"complete-drawing/dragon-01/reference_full.png","group":"fantasy"}','ready',0,1,47,'خيال,متوسط','complete-dragon-01'),
('complete-castle-01','complete','قلعة','Castle',7,9,'مفصل','complete-drawing/castle-01/challenge.png','complete-drawing/castle-01/thumbnail.jpg','{"reference_full":"complete-drawing/castle-01/reference_full.png","group":"fantasy","tag":"تناظر"}','ready',0,1,48,'خيال,تناظر,صعب','complete-castle-01'),
('complete-cloud-house-01','complete','بيت فوق السحاب','Cloud House',7,9,'مفصل','complete-drawing/cloud-house-01/challenge.png','complete-drawing/cloud-house-01/thumbnail.jpg','{"reference_full":"complete-drawing/cloud-house-01/reference_full.png","group":"fantasy"}','ready',0,1,49,'خيال,صعب','complete-cloud-house-01'),
('complete-floating-island-01','complete','جزيرة طائرة','Floating Island',7,9,'مفصل','complete-drawing/floating-island-01/challenge.png','complete-drawing/floating-island-01/thumbnail.jpg','{"reference_full":"complete-drawing/floating-island-01/reference_full.png","group":"fantasy"}','ready',0,1,50,'خيال,صعب','complete-floating-island-01');
