-- 0080 — الكتالوج الفعلي 72 هدفا مستخرج من المحتوى المكتوب docs/content/90-learning-objectives.md
-- القاعدة 5 طبقت: 27 معرفا قديما بلا محتوى بقي في DB للتوافق، 72 الجديد يضاف بـ INSERT OR IGNORE
-- مصدر الحقيقة للمسارات والعمر هو نفس الملف، والمهارة مقربة من skills الموجودة (25 صفا)
-- لا يحذف القديم: حلقات قد تشير اليه، يبقى حتى ترحيل ربط الحلقات
PRAGMA foreign_keys=ON;

-- Helper: titles cleaned (strip 🔴 and **)
INSERT OR IGNORE INTO learning_objectives (id, code, title_ar, description_ar, skill_id, age_min, age_max, measurable_criteria) VALUES
 ('objective-lang-vocab-match_word_image','lang.vocab.match_word_image','يطابق الكلمة المنطوقة بصورتها','يطابق الكلمة المنطوقة بصورتها من 4 ازواج بنسبة 75%','reading',3,5,'يطابق 3 من 4 ازواج صحيحة من اول محاولة'),
 ('objective-lang-phonics-first_sound','lang.phonics.first_sound','يميز الصوت الاول في الكلمة','يميز الصوت الاول في الكلمة','reading',3,5,'يميز الصوت الاول في 4 من 5 كلمات'),
 ('objective-lang-letters-trace_form','lang.letters.trace_form','يتتبع شكل الحرف بترتيب رسم صحيح','تتبع شكل الحرف بترتيب رسم صحيح الجسم قبل النقاط','writing',3,5,'يتتبع الحرف بتغطية 70% وتسامح 20dp'),
 ('objective-lang-vocab-name_objects','lang.vocab.name_objects','يسمي عناصر مالوفة من محيطه','يسمي عناصر مالوفة من محيطه','reading',3,5,'يسمي 4 من 5 عناصر مالوفة'),
 ('objective-math-count-one_to_one','math.count.one_to_one','يربط كل عنصر بواحد — مطابقة احادية','مطابقة احادية واحد لواحد','counting',3,5,'يطابق كل عنصر بواحد بلا تكرار او اغفال'),
 ('objective-math-count-to_five','math.count.to_five','يعد حتى 5','يعد حتى 5','counting',3,5,'يعد حتى 5 عد تسلسلي صحيح'),
 ('objective-math-count-to_ten','math.count.to_ten','يعد حتى 10','يعد حتى 10','counting',6,8,'يعد حتى 10 تسلسلي'),
 ('objective-math-compare-more_less','math.compare.more_less','يقارن مجموعتين','يقارن مجموعتين اكثر/اقل/متساو','observation',3,8,'يحدد ايهما اكثر بدقة 80%'),
 ('objective-math-pattern-complete','math.pattern.complete','يكمل نمطا','يكمل نمطا AB او متزايد','pattern_recognition',3,8,'يكمل 4 من 5 انماط'),
 ('objective-math-add-visual_sum','math.add.visual_sum','يجمع بصريا','يجمع بصريا مجموعتين صغيرتين','addition',6,8,'يجمع مجموعتين حتى 5 + 5'),
 ('objective-math-subtract-visual','math.subtract.visual','يطرح بصريا','يطرح بصريا بازالة عناصر','addition',6,8,'يطرح حتى 10 - 3 بصريا'),
 ('objective-sci-body-organ_function','sci.body.organ_function','يربط العضو بوظيفته','يربط العضو بوظيفته القلب/الدماغ/المعدة','observation',6,8,'يربط 4 اعضاء بوظائفها'),
 ('objective-sci-body-senses','sci.body.senses','يميز الحواس ووظائفها','يميز الحواس الخمس ووظائفها','observation',6,8,'يسمي الحاسة والوظيفة'),
 ('objective-sci-body-breathing','sci.body.breathing','يشرح كيف يدخل الهواء ويخرج','يدخل الهواء ويخرج عبر الرئتين','observation',6,8,'يتتبع مسار الهواء انف-رئة-زفير'),
 ('objective-sci-body-skeleton','sci.body.skeleton','يربط العظام بالحركة','العظام تدعم وتحمي وتساعد الحركة','observation',6,8,'يربط العظام بالحركة'),
 ('objective-sci-body-digestion','sci.body.digestion','يتتبع رحلة الطعام الى طاقة','رحلة الطعام فم-معدة-امعاء-طاقة','observation',6,8,'يتتبع رحلة الطعام بترتيب'),
 ('objective-sci-body-hygiene','sci.body.hygiene','يربط النظافة بالوقاية','النظافة تقي من الجراثيم','self_regulation',6,8,'يربط غسل اليدين بالوقاية'),
 ('objective-sci-physics-refraction','sci.physics.refraction','يفسر انكسار الضوء','انكسار الضوء عند تغير الوسط','observation',9,12,'يفسر انكسار القلم في الماء'),
 ('objective-sci-physics-air_pressure','sci.physics.air_pressure','يفسر اثر ضغط الهواء','ضغط الهواء يحمل/يدفع','observation',9,12,'يفسر لماذا لا يسقط الماء بضغط الهواء'),
 ('objective-sci-space-moon_phases','sci.space.moon_phases','يفسر سبب اطوار القمر','سبب اطوار القمر انعكاس ضوء الشمس','observation',9,12,'يفسر سبب اطوار القمر بتدوير النموذج'),
 ('objective-sci-energy-conversion','sci.energy.conversion','يتتبع تحول الطاقة','تحول الطاقة ضوئية-حرارية-حركية','observation',9,12,'يتتبع تحول الطاقة في مثالين'),
 ('objective-sci-env-water_cycle','sci.env.water_cycle','يفسر دورة الماء','تبخر-تكاثف-هطول','observation',9,12,'يفسر دورة الماء بترتيب'),
 ('objective-sci-health-sleep_function','sci.health.sleep_function','يربط النوم بوظيفته','النوم يرمم الجسم والذاكرة','self_regulation',9,12,'يربط النوم بالتركيز والنمو'),
 ('objective-sci-method-observe_predict','sci.method.observe_predict','يصوغ توقعا قبل التجربة','يصوغ توقعا قبل التجربة مبني على ملاحظة','observation',6,8,'يصوغ توقعا واحدا قبل التجربة'),
 ('objective-sci-method-classify_test','sci.method.classify_test','يصنف بنتيجة اختبار','يصنف بنتيجة اختبار يطفو/يغرق','observation',6,8,'يصنف 4 اشياء بنتيجة اختبار'),
 ('objective-sci-method-test_hypothesis','sci.method.test_hypothesis','يختبر فرضية','يختبر فرضية بتجربة واحدة','observation',6,8,'يختبر فرضية ويقرا النتيجة'),
 ('objective-sci-method-record_observe','sci.method.record_observe','يسجل ملاحظة على مدى ايام','يسجل ملاحظة يومية لجسم/نبات','observation',6,8,'يسجل ملاحظة 3 ايام'),
 ('objective-sci-method-change_one_variable','sci.method.change_one_variable','يثبت متغيرا ويغير اخر','يثبت متغيرا ويغير اخر ويقيس الاثر','observation',6,8,'يثبت الماء ويغير الضوء ويقيس الطول'),
 ('objective-sci-method-evidence_claim','sci.method.evidence_claim','يميز الدعوى من دليلها','يميز الدعوى من دليلها','observation',6,8,'يميز جملة دعوى من دليل في نص قصير'),
 ('objective-sci-energy-solar_conversion','sci.energy.solar_conversion','يحول ضوءا الى حركة','يحول ضوءا الى حركة بمحرك شمسي','observation',9,12,'يحول ضوءا الى حركة في نموذج'),
 ('objective-sci-engineering-structure_shape','sci.engineering.structure_shape','يربط الشكل بالمتانة','المثلث والقوس اكثر متانة','observation',9,12,'يربط الشكل بالمتانة في جسر/برج'),
 ('objective-sci-energy-series_circuit','sci.energy.series_circuit','يبني دائرة على التوالي','يبني دائرة على التوالي بطارية-مصباح-مفتاح','observation',9,12,'يبني دائرة على التوالي تضيء'),
 ('objective-sci-method-null_result','sci.method.null_result','يقرا نتيجة سلبية بوصفها نتيجة','لم يحدث شيء نتيجة تسجل لا فشلا','observation',9,12,'يسجل لا اثر بوصفه نتيجة'),
 ('objective-sci-physics-center_of_mass','sci.physics.center_of_mass','يجد مركز الكتلة','يجد مركز الكتلة ليوازن شكلا','observation',9,12,'يجد نقطة التوازن'),
 ('objective-sci-method-design_experiment','sci.method.design_experiment','يصمم تجربة كاملة','يصمم تجربة سؤال-فرضية-متغيرات-قياس-استنتاج','observation',9,12,'يصمم تجربة كاملة بمتغير واحد'),
 ('objective-val-honesty-return_found','val.honesty.return_found','يرد ما وجده وليس له','يرد ما وجده وليس له الى صاحبه/الامانة','honesty',6,8,'يختار رد المفقود في سيناريو'),
 ('objective-val-sharing-with_boundaries','val.sharing.with_boundaries','يشارك مع حفظ حقه في الرفض','يشارك مع حفظ حقه في الرفض باحترام','empathy',6,8,'يختار مشاركة مع حدود في موقفين'),
 ('objective-val-patience-wait_turn','val.patience.wait_turn','ينتظر دوره ويطلب حقه بهدوء','ينتظر دوره ويطلب حقه بهدوء','self_regulation',6,8,'ينتظر دوره ويطلب بكلمة هادئة'),
 ('objective-val-responsibility-build_system','val.responsibility.build_system','يصنع نظام تذكير لا يعتمد على النية','يصنع نظام تذكير ورقي/رقمي','self_regulation',6,8,'يصنع نظام تذكير واحد'),
 ('objective-val-kindness-initiate_words','val.kindness.initiate_words','يبدا بكلمة طيبة','يبدا بكلمة طيبة صباح الخير شكرا','empathy',6,8,'يبدا بكلمة طيبة في سيناريو'),
 ('objective-val-apology-repair_four_steps','val.apology.repair_four_steps','يعتذر باربع خطوات بلا عقاب على الاعتراف','اعتذار اعتراف-مسؤولية-اصلاح-عدم تكرار','honesty',6,8,'يرتب اعتذار باربع خطوات'),
 ('objective-story-habitat-match_home','story.habitat.match_home','يطابق كل مخلوق بمكانه','يطابق كل مخلوق بمكانه بيت/عش/جحر','observation',3,5,'يطابق 4 مخلوقات ببيوتها'),
 ('objective-story-routine-bedtime_steps','story.routine.bedtime_steps','يرتب خطوات الاستعداد للنوم','يرتب خطوات الاستعداد للنوم','self_regulation',3,5,'يرتب 4 خطوات نوم'),
 ('objective-story-sequence-small_steps','story.sequence.small_steps','يرتب هدفا كبيرا خطوات صغيرة والاستراحة خطوة','يرتب هدفا كبيرا خطوات صغيرة والاستراحة خطوة','memory',6,8,'يرتب 4 خطوات هدف كبير'),
 ('objective-story-cause-seed_travel','story.cause.seed_travel','يتتبع كيف تنتقل البذور','كيف تنتقل البذور ريح ماء حيوان','observation',6,8,'يتتبع طريقتين لنقل البذور'),
 ('objective-story-social-include_difference','story.social.include_difference','يجد لعبة تجمع ميلين مختلفين','يجد لعبة تجمع ميلين مختلفين','empathy',6,8,'يقترح لعبة تجمع ميلين'),
 ('objective-story-value-object_memory','story.value.object_memory','يرتب غرض صورة حكاية بطاقة ذاكرة','يرتب غرض-صورة-حكاية-بطاقة ذاكرة','memory',6,8,'يرتب 4 مراحل ذكرى الغرض'),
 ('objective-story-observe-object_vs_reflection','story.observe.object_vs_reflection','يفرق الشيء من صورته المنعكسة','يفرق الشيء من صورته المنعكسة في ماء/مراة','observation',6,8,'يفرق الشيء من انعكاسه في مثالين'),
 ('objective-skill-ct-sequence','skill.ct.sequence','يرتب اوامر بتسلسل صحيح','يرتب اوامر بتسلسل صحيح ابدا-تحرك-توقف','coding',9,12,'يرتب 4 اوامر تسلسل صحيح'),
 ('objective-skill-ct-debug','skill.ct.debug','يجد اول امر انحرف ويصلحه بتعديل واحد','يجد اول امر انحرف ويصلحه بتعديل واحد','coding',9,12,'يجد الخطا الاول ويصلحه'),
 ('objective-skill-ct-loop','skill.ct.loop','يستعمل التكرار ويعرف انه لا يقلل الخطوات','يستعمل التكرار ويعرف انه تنظيم لا تقليل','coding',9,12,'يكتب تكرارا لثلاث حركات'),
 ('objective-skill-ct-condition','skill.ct.condition','يكتب شرطا بفرعيه ويعرف انه لحظي','يكتب اذا-والا ويعرف ان الشرط لحظي','coding',9,12,'يكتب شرطا بفرعيه'),
 ('objective-skill-ct-function','skill.ct.function','يجد النمط ثم يسميه','يجد النمط ثم يسميه دالة','coding',9,12,'يجد نمطا ويسميه'),
 ('objective-skill-ct-compose','skill.ct.compose','يقسم مشروعا مراحل ويختبر كل مرحلة','يقسم مشروعا مراحل ويختبر كل مرحلة','coding',9,12,'يقسم مشروعا مرحلتين ويختبر'),
 ('objective-hist-civ-water_engineering','hist.civ.water_engineering','يعرف ان نقل الماء قياس لا فكرة','نقل الماء قياس وانحدار وكميات','observation',9,12,'يفسر نقل الماء كقياس لا فكرة'),
 ('objective-hist-civ-observation','hist.civ.observation','يفرق القياس من التفسير','يفرق القياس المجرد من تفسير السبب','observation',9,12,'يفرق قياسا من تفسير في نص'),
 ('objective-hist-civ-translation','hist.civ.translation','يعرف ان ما بقي هو ما نسخ','ما بقي هو ما نسخ في بيت الحكمة','memory',9,12,'يفسر لماذا بقي المنسوخ'),
 ('objective-hist-civ-trade_geography','hist.civ.trade_geography','يقرا الطريق بالماء والممرات','يقرا الطريق بالماء والممرات','map_reading',9,12,'يقرا طريقا نهريا/بحريا على خريطة'),
 ('objective-hist-civ-writing_medium','hist.civ.writing_medium','يربط ثمن الوسيط بما يكتب','ثمن الوسيط ورق/بردي يحدد ما يكتب','observation',9,12,'يربط الوسيط بالمحتوى'),
 ('objective-hist-timeline-place_event','hist.timeline.place_event','يضع الحدث في قرنه بهامش مقبول','يضع الحدث في قرنه بهامش +-100 سنة','memory',9,12,'يضع حدثا في قرنه بهامش'),
 ('objective-hist-geo-place_location','hist.geo.place_location','يحدد موضعا على خريطة','يحدد موضعا على خريطة صماء','map_reading',9,12,'يحدد موضعين على خريطة بخريطة اساس محايدة'),
 ('objective-world-color-identify_yellow','world.color.identify_yellow','يسمي لونا ويجده','يسمي الاصفر ويجده في الصورة','observation',3,5,'يسمي الاصفر ويشير اليه'),
 ('objective-world-color-sort_two','world.color.sort_two','يجمع الاشياء بخصيصة مقدمة العد','يجمع الاشياء بخصيصة لونين','observation',3,5,'يجمع اشياء بلونين'),
 ('objective-world-shape-circle_square','world.shape.circle_square','يميز الشكل بلا مساعدة اللون','يميز الدائرة من المربع بلا لون','shape_recognition',3,5,'يميز دائرة من مربع بلا لون'),
 ('objective-world-size-compare','world.size.compare','يقارن شيئين والحجم نسبي','يقارن شيئين اكبر/اصغر والحجم نسبي','observation',3,5,'يقارن شيئين اكبر/اصغر'),
 ('objective-world-pattern-ab_repeat','world.pattern.ab_repeat','يكمل نمط أ ب','يكمل نمط أ ب احمر-ازرق','pattern_recognition',3,5,'يكمل نمط AB ثلاث مرات'),
 ('objective-world-reason-combine_clues','world.reason.combine_clues','يجمع دلائل والواحد لا يميز','يجمع دلائل والواحد لا يميز','observation',6,8,'يجمع دليلين ليعرف الحيوان'),
 ('objective-world-collab-divide_and_order','world.collab.divide_and_order','يقسم مهمة ويرتبها','يقسم مهمة ويرتب خطواتها','self_regulation',6,8,'يقسم مهمة 3 خطوات ويرتبها'),
 ('objective-world-space-map_landmarks','world.space.map_landmarks','يقرا خريطة بالعلامات لا بالاتجاهات','يقرا خريطة بالعلامات لا شمال/جنوب','map_reading',6,8,'يقرا خريطة بعلامتين'),
 ('objective-world-observe-classify_sounds','world.observe.classify_sounds','يعرف المجهول بمقارنته بالمعلوم','يعرف المجهول بمقارنته بالمعلوم تصنيف اصوات','observation',6,8,'يصنف صوتا مجهولا بمقارنته'),
 ('objective-world-reason-correlation_not_cause','world.reason.correlation_not_cause','يفرق حدث معه من سببه','يفرق ليس الفارق ليس سببا ترابط لا سببية','observation',6,8,'يفرق ترابطا من سبب في مثال حديقة'),
 ('objective-world-observe-water_moves','world.observe.water_moves','يلاحظ ان الماء ينتقل ولا يختفي','يلاحظ ان الماء ينتقل ولا يختفي دورة صغرى','observation',6,8,'يلاحظ انتقال الماء ولا اختفاءه');

-- Tracks
INSERT OR IGNORE INTO learning_objective_tracks (objective_id, track_id) VALUES
 ('objective-lang-vocab-match_word_image','preschool'),
 ('objective-lang-phonics-first_sound','preschool'),
 ('objective-lang-letters-trace_form','preschool'),
 ('objective-lang-vocab-name_objects','preschool'),
 ('objective-math-count-one_to_one','preschool'),
 ('objective-math-count-to_five','preschool'),
 ('objective-math-count-to_ten','kids'),
 ('objective-math-compare-more_less','preschool'),('objective-math-compare-more_less','kids'),
 ('objective-math-pattern-complete','preschool'),('objective-math-pattern-complete','kids'),
 ('objective-math-add-visual_sum','kids'),
 ('objective-math-subtract-visual','kids'),
 ('objective-sci-body-organ_function','kids'),
 ('objective-sci-body-senses','kids'),
 ('objective-sci-body-breathing','kids'),
 ('objective-sci-body-skeleton','kids'),
 ('objective-sci-body-digestion','kids'),
 ('objective-sci-body-hygiene','kids'),
 ('objective-sci-physics-refraction','junior'),
 ('objective-sci-physics-air_pressure','junior'),
 ('objective-sci-space-moon_phases','junior'),
 ('objective-sci-energy-conversion','junior'),
 ('objective-sci-env-water_cycle','junior'),
 ('objective-sci-health-sleep_function','junior'),
 ('objective-sci-method-observe_predict','kids'),
 ('objective-sci-method-classify_test','kids'),
 ('objective-sci-method-test_hypothesis','kids'),
 ('objective-sci-method-record_observe','kids'),
 ('objective-sci-method-change_one_variable','kids'),
 ('objective-sci-method-evidence_claim','kids'),
 ('objective-sci-energy-solar_conversion','junior'),
 ('objective-sci-engineering-structure_shape','junior'),
 ('objective-sci-energy-series_circuit','junior'),
 ('objective-sci-method-null_result','junior'),
 ('objective-sci-physics-center_of_mass','junior'),
 ('objective-sci-method-design_experiment','junior'),
 ('objective-val-honesty-return_found','kids'),
 ('objective-val-sharing-with_boundaries','kids'),
 ('objective-val-patience-wait_turn','kids'),
 ('objective-val-responsibility-build_system','kids'),
 ('objective-val-kindness-initiate_words','kids'),
 ('objective-val-apology-repair_four_steps','kids'),
 ('objective-story-habitat-match_home','preschool'),
 ('objective-story-routine-bedtime_steps','preschool'),
 ('objective-story-sequence-small_steps','kids'),
 ('objective-story-cause-seed_travel','kids'),
 ('objective-story-social-include_difference','kids'),
 ('objective-story-value-object_memory','kids'),
 ('objective-story-observe-object_vs_reflection','kids'),
 ('objective-skill-ct-sequence','junior'),
 ('objective-skill-ct-debug','junior'),
 ('objective-skill-ct-loop','junior'),
 ('objective-skill-ct-condition','junior'),
 ('objective-skill-ct-function','junior'),
 ('objective-skill-ct-compose','junior'),
 ('objective-hist-civ-water_engineering','junior'),
 ('objective-hist-civ-observation','junior'),
 ('objective-hist-civ-translation','junior'),
 ('objective-hist-civ-trade_geography','junior'),
 ('objective-hist-civ-writing_medium','junior'),
 ('objective-hist-timeline-place_event','junior'),
 ('objective-hist-geo-place_location','junior'),
 ('objective-world-color-identify_yellow','preschool'),
 ('objective-world-color-sort_two','preschool'),
 ('objective-world-shape-circle_square','preschool'),
 ('objective-world-size-compare','preschool'),
 ('objective-world-pattern-ab_repeat','preschool'),
 ('objective-world-reason-combine_clues','kids'),
 ('objective-world-collab-divide_and_order','kids'),
 ('objective-world-space-map_landmarks','kids'),
 ('objective-world-observe-classify_sounds','kids'),
 ('objective-world-reason-correlation_not_cause','kids'),
 ('objective-world-observe-water_moves','kids');

-- Backfill secondary skills for letter tracing (writing primary already, add motor)
INSERT OR IGNORE INTO learning_objective_skills (objective_id, skill_id, role)
SELECT 'objective-lang-letters-trace_form','letter_formation','primary' WHERE EXISTS (SELECT 1 FROM learning_objectives WHERE id='objective-lang-letters-trace_form' AND skill_id='writing');
INSERT OR IGNORE INTO learning_objective_skills (objective_id, skill_id, role) VALUES
 ('objective-lang-letters-trace_form','fine_motor','secondary'),
 ('objective-lang-letters-trace_form','visual_motor_integration','secondary'),
 ('objective-lang-letters-trace_form','letter_formation','secondary'),
 ('objective-sci-method-change_one_variable','hand_eye_coordination','secondary');

-- Ensure primary mapping mirrors learning_objectives.skill_id
INSERT OR IGNORE INTO learning_objective_skills (objective_id, skill_id, role)
SELECT id, skill_id, 'primary' FROM learning_objectives WHERE skill_id IS NOT NULL AND id LIKE 'objective-%' AND code IN (
 'lang.vocab.match_word_image','lang.phonics.first_sound','lang.letters.trace_form','lang.vocab.name_objects',
 'math.count.one_to_one','math.count.to_five','math.count.to_ten','math.compare.more_less','math.pattern.complete','math.add.visual_sum','math.subtract.visual',
 'sci.body.organ_function','sci.body.senses','sci.body.breathing','sci.body.skeleton','sci.body.digestion','sci.body.hygiene',
 'sci.physics.refraction','sci.physics.air_pressure','sci.space.moon_phases','sci.energy.conversion','sci.env.water_cycle','sci.health.sleep_function',
 'sci.method.observe_predict','sci.method.classify_test','sci.method.test_hypothesis','sci.method.record_observe','sci.method.change_one_variable','sci.method.evidence_claim',
 'sci.energy.solar_conversion','sci.engineering.structure_shape','sci.energy.series_circuit','sci.method.null_result','sci.physics.center_of_mass','sci.method.design_experiment',
 'val.honesty.return_found','val.sharing.with_boundaries','val.patience.wait_turn','val.responsibility.build_system','val.kindness.initiate_words','val.apology.repair_four_steps',
 'story.habitat.match_home','story.routine.bedtime_steps','story.sequence.small_steps','story.cause.seed_travel','story.social.include_difference','story.value.object_memory','story.observe.object_vs_reflection',
 'skill.ct.sequence','skill.ct.debug','skill.ct.loop','skill.ct.condition','skill.ct.function','skill.ct.compose',
 'hist.civ.water_engineering','hist.civ.observation','hist.civ.translation','hist.civ.trade_geography','hist.civ.writing_medium','hist.timeline.place_event','hist.geo.place_location',
 'world.color.identify_yellow','world.color.sort_two','world.shape.circle_square','world.size.compare','world.pattern.ab_repeat','world.reason.combine_clues','world.collab.divide_and_order','world.space.map_landmarks','world.observe.classify_sounds','world.reason.correlation_not_cause','world.observe.water_moves'
);
