// Loads the completion pass into D1: 13 book manuscripts, 14 game specs (with engine remap),
// 7 activity specs, all project->series links, 2 presenter characters, one repaired story,
// and the genuinely-new learning objectives.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = 'F:\\Projects\\cartoonapp';
const rd = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''));
const qr = (p) => { const j = rd(p); return (Array.isArray(j) ? j : [j]).flatMap((x) => x.results ?? []); };

const books = rd(path.join(ROOT, 'docs/content/planets/_manifest-books.json'));
const games = rd(path.join(ROOT, 'docs/content/planets/_manifest-games.json'));
const acts = rd(path.join(ROOT, 'docs/content/planets/_manifest-activities.json'));
const slate = rd('_manifests.json').manifests;
const seriesRows = qr('_ref_series.json');
const seriesBySlug = new Map(seriesRows.map((r) => [r.slug, r]));
const epRows = qr('_ref_episodes.json');
const epKey = new Map(epRows.map((r) => [`${r.series_slug}#${r.episode_number}`, r.id]));

const q = (v) => (v === null || v === undefined || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined || Number.isNaN(Number(v)) ? 'NULL' : String(Number(v)));
const j = (v) => q(JSON.stringify(v ?? []));
const jo = (v) => q(JSON.stringify(v ?? {}));

const out = [];
const say = (s) => out.push(s);
let seq = 0;
const audit = (action, type, id, details) => {
  seq += 1;
  say(`INSERT INTO audit_logs (id, actor_id, action, entity_type, entity_id, details) VALUES (${q(`audit-completion-${String(seq).padStart(4, '0')}`)}, 'content-completion-pass', ${q(action)}, ${q(type)}, ${q(id)}, ${q(JSON.stringify(details))});`);
};
const tracksForRange = (a, b) => ['preschool', 'kids', 'junior'].filter((t) => {
  const bd = t === 'preschool' ? [3, 5] : t === 'kids' ? [6, 8] : [9, 12];
  return a <= bd[1] && b >= bd[0];
});
const objId = (code) => `objective-${code.replace(/\./g, '-')}`;

const stats = { objectives: 0, books: 0, book_pages: 0, games: 0, activities: 0, project_links: 0, characters: 0, story_pages: 0, archived_eps: 0 };

say('-- Majarra content completion pass. Generated by scripts/_audit_load_completion.mjs');
say('-- Everything stays draft. No media is claimed to exist. No game is claimed implemented.');
say('');

/* -------- PART 1: the genuinely new learning objectives -------- */
say('-- PART 1: five objectives that the authored sources use but the table did not hold.');
say('--   The other 18 unregistered codes found in the sources are NOT objectives - they are');
say('--   content-pack item keys and safety notes inside game packs (hist.event.*, hist.place.*,');
say('--   hist.explain.*, hist.anchor.*, sci.safety.*). Registering those as curriculum objectives');
say('--   would create exactly the meaningless field-filling objectives we are trying to avoid.');
const NEW_OBJECTIVES = [
  ['world.observe.classify_nature', 'يصنّف ما يلاحظه في الطبيعة إلى فئات يسمّيها بنفسه', 'يصنّف 8 مشاهدات إلى فئتين يسمّيهما، في 3 من 4 محاولات', 'observation', 6, 8],
  ['sci.physics.identify_forces', 'يحدّد القوّة المؤثّرة في مشهد يومي ويسمّي اتجاهها', 'يحدّد القوّة واتجاهها في 5 من 6 مشاهد', null, 9, 12],
  ['hist.civ.problem_solution_evidence', 'يربط ابتكارًا بالمشكلة التي حلّها، ويذكر الدليل على ذلك', 'يربط 4 ابتكارات بمشكلاتها ويذكر دليلًا لكل منها، في 3 من 4', 'craft', 9, 12],
  ['hist.timeline.place_event', 'يضع حدثًا في موضعه الصحيح على خط زمن نسبي', 'يضع 5 أحداث في ترتيبها الصحيح على خط زمن، في 4 من 5 محاولات', null, 9, 12],
  ['hist.geo.place_location', 'يحدّد موقع مكان على خريطة ويعلّل الموقع بسبب جغرافي واحد', 'يحدّد 4 مواقع ويعلّل كل واحد بسبب جغرافي، في 3 من 4', 'map_reading', 9, 12],
];
for (const [code, title, crit, skill, amin, amax] of NEW_OBJECTIVES) {
  const id = objId(code);
  say(`INSERT OR IGNORE INTO learning_objectives (id, code, title_ar, description_ar, skill_id, age_min, age_max, measurable_criteria) VALUES (${q(id)}, ${q(code)}, ${q(title)}, ${q(crit)}, ${q(skill)}, ${n(amin)}, ${n(amax)}, ${q(crit)});`);
  for (const t of tracksForRange(amin, amax)) say(`INSERT OR IGNORE INTO learning_objective_tracks (objective_id, track_id) VALUES (${q(id)}, ${q(t)});`);
  stats.objectives += 1;
}
audit('bulk_create', 'learning_objective', null, { count: NEW_OBJECTIVES.length, source: 'authored books, games and activities' });
say('');

/* -------- PART 2: 13 book manuscripts -------- */
say('-- PART 2: the 13 books that held only a title. Real manuscripts, 184 pages total.');
for (const b of books.books) {
  const pages = b.pages.map((p) => ({
    page: p.page, role: p.role, text_ar: p.text_ar,
    illustration_brief: p.illustration_brief, exercise: p.exercise ?? null,
  }));
  const sets = [
    `pages=${j(pages)}`,
    `reading_level=${q(b.reading_level)}`,
    b.interaction_mode ? `interaction_mode=${q(b.interaction_mode)}` : null,
    b.supervision_level ? `supervision_level=${q(b.supervision_level)}` : null,
    `languages=${j(b.languages ?? ['ar'])}`,
    `default_language=${q(b.default_language ?? 'ar')}`,
    `status='draft'`,
    `updated_at=datetime('now')`,
  ].filter(Boolean);
  say(`UPDATE books SET ${sets.join(', ')} WHERE id=${q(b.id)};`);
  stats.books += 1; stats.book_pages += pages.length;
  audit('update', 'book', b.id, { pages: pages.length, source: b.source_file, editorial: 'manuscript authored' });
}
say('');

/* -------- PART 3: 14 game design specs + engine remap -------- */
say('-- PART 3: the 14 games that held only a title. Full design specs, and each is repointed');
say('--   from a legacy placeholder engine id to the documented engine contract it actually needs.');
for (const g of games.games) {
  const linkedEp = g.linked_episode_number ? epKey.get(`${g.series_slug}#${g.linked_episode_number}`) : null;
  const pack = {
    pack_id: g.id, engine: g.engine, engine_justification: g.engine_justification,
    core_mechanic: g.core_mechanic, gameplay_loop: g.gameplay_loop, levels: g.levels,
    difficulty_progression: g.difficulty_progression, success_rule: g.success_rule,
    failure_rule: g.failure_rule, scoring: g.scoring, rewards: g.rewards,
    educational_feedback: g.educational_feedback, accessibility: g.accessibility,
    spec: g.content_pack ?? {}, source_file: g.source_file,
    implementation_status: 'design only - not implemented',
    production_required: g.production_required ?? ['game_art', 'voice_prompts', 'engine_implementation'],
  };
  say(`UPDATE games SET engine_id=${q(g.engine)}, episode_id=${linkedEp ? q(linkedEp) : 'NULL'}, learning_objective_id=${q(objId(g.objective_code))}, reading_level=${q(g.reading_level)}, interaction_mode=${q(g.interaction_mode)}, supervision_level=${q(g.supervision_level)}, difficulty=${q(g.difficulty)}, content_pack=${jo(pack)}, instructions_ar=${q(g.instructions_ar)}, max_attempts=${n(g.max_attempts)}, help_system=${jo(g.help_system)}, status='draft', updated_at=datetime('now') WHERE id=${q(g.id)};`);
  stats.games += 1;
  audit('update', 'game', g.id, { engine_from: 'legacy placeholder', engine_to: g.engine, levels: (g.levels ?? []).length, implementation_status: 'design only' });
}
say('');

/* -------- PART 4: 7 activity specs -------- */
say('-- PART 4: the 7 activities that held only a title.');
for (const a of acts.activities) {
  const sr = seriesBySlug.get(a.series_slug);
  const linkedEp = a.linked_episode_number ? epKey.get(`${a.series_slug}#${a.linked_episode_number}`) : null;
  const desc = [a.description_ar, a.preparation && `التحضير: ${a.preparation}`,
    a.expected_result && `النتيجة المتوقّعة: ${a.expected_result}`,
    a.explanation_ar && `التفسير: ${a.explanation_ar}`,
    a.parent_involvement && `دور ولي الأمر: ${a.parent_involvement}`].filter(Boolean).join('\n\n');
  say(`UPDATE projects SET description_ar=${q(desc)}, materials=${j(a.materials)}, steps=${j(a.steps)}, safety_notes=${q(a.safety_notes)}, supervision_level=${q(a.supervision_level)}, learning_objective_ids=${j(a.objective_code ? [objId(a.objective_code)] : [])}, series_id=${sr ? q(sr.id) : 'NULL'}, episode_id=${linkedEp ? q(linkedEp) : 'NULL'}, estimated_minutes=${n(a.estimated_minutes)}, status='draft', updated_at=datetime('now') WHERE id=${q(a.id)};`);
  stats.activities += 1;
  audit('update', 'project', a.id, { series: a.series_slug, episode: a.linked_episode_number, steps: a.steps.length, source: a.source_file });
}
say('');

/* -------- PART 5: attach the 21 already-authored activities to their series -------- */
say('-- PART 5: the projects table gained series_id/episode_id/estimated_minutes in migration 0018.');
say('--   Backfill the link for the activities authored in the slate pass, which until now recorded');
say('--   their parent episode only in the source manifest.');
for (const m of slate) {
  const sr = seriesBySlug.get(m.series.slug);
  if (!sr) continue;
  for (const pr of m.projects ?? []) {
    const linkedEp = pr.related_episode ? epKey.get(`${m.series.slug}#${pr.related_episode}`) : null;
    const mins = Number(String(pr.duration ?? pr.estimated_minutes ?? '').match(/\d+/)?.[0]) || null;
    say(`UPDATE projects SET series_id=${q(sr.id)}${linkedEp ? `, episode_id=${q(linkedEp)}` : ''}${mins ? `, estimated_minutes=${n(mins)}` : ''}, updated_at=datetime('now') WHERE id=${q(`project-${pr.slug}`)};`);
    stats.project_links += 1;
  }
}
audit('bulk_update', 'project', null, { field: 'series_id/episode_id/estimated_minutes', reason: 'activities could not be attached to their content before migration 0018' });
say('');

/* -------- PART 6: 2 presenter characters -------- */
say('-- PART 6: the two `presenter` series had no presenter record. A presenter series is defined');
say('--   by exactly one host who addresses the child directly, so this was a real gap.');
let ci = 0;
for (const c of acts.characters) {
  ci += 1;
  const sr = seriesBySlug.get(c.series_slug);
  if (!sr) { say(`-- SKIPPED character ${c.name_ar}: series ${c.series_slug} not found`); continue; }
  const desc = [c.description_ar,
    c.behavioural_rules?.length && `قواعد سلوكية: ${c.behavioural_rules.join(' · ')}`,
    c.relationships && `العلاقة بالمشاهد: ${c.relationships}`,
    c.educational_role && `الدور التعليمي: ${c.educational_role}`,
    c.recurring_behaviour && `سلوك متكرّر: ${c.recurring_behaviour}`,
    `الموجز البصري: ${c.visual_brief}`,
    c.expression_requirements?.length && `التعبيرات المطلوبة: ${c.expression_requirements.join(' · ')}`,
    c.voice_direction && `توجيه الصوت: ${c.voice_direction}`,
    'حالة الأصول: لا توجد رسوم ولا تسجيل صوتي ولا اختيار ممثّل — الإنتاج مطلوب.'].filter(Boolean).join('\n\n');
  say(`INSERT OR IGNORE INTO characters (id, series_id, name_ar, role, age, description_ar, traits, speech_style, reference_images, expressions, outfits, languages, status) VALUES (${q(`character-${c.series_slug}-presenter`)}, ${q(sr.id)}, ${q(c.name_ar)}, ${q(c.role)}, ${n(c.age)}, ${q(desc)}, ${j(c.traits)}, ${q(c.speech_style)}, '[]', '{}', '[]', ${j(['ar'])}, 'active');`);
  stats.characters += 1;
  audit('create', 'character', `character-${c.series_slug}-presenter`, { series: c.series_slug, role: c.role, artwork: 'none - production required' });
}
say('');

/* -------- PART 7: the repaired story -------- */
say('-- PART 7: story-01-bird-home carried 8 pages of real text in a non-standard table format,');
say('--   so none of it could be loaded. The file was restructured into the standard format with');
say('--   all 8 pages preserved verbatim; load them now.');
const sr = acts.story_repair;
for (const p of sr.pages ?? []) {
  const pid = `page-bird-home-${String(p.page_number).padStart(3, '0')}`;
  const motion = /static/.test(p.motion) ? 'static' : (/pan/.test(p.motion) ? 'pan_slow' : 'kenburns_slow');
  say(`INSERT OR IGNORE INTO story_pages (id, story_id, page_number, layout, transition, sort_order) VALUES (${q(pid)}, 'story-bird-home', ${n(p.page_number)}, ${q(p.layout ?? 'full_bleed')}, ${q(motion)}, ${n(p.page_number)});`);
  say(`INSERT OR IGNORE INTO story_page_localizations (page_id, language, body_text, alt_text) VALUES (${q(pid)}, 'ar', ${q(p.text_ar)}, ${q(p.illustration_brief)});`);
  stats.story_pages += 1;
}
audit('update', 'story', 'story-bird-home', { pages_loaded: stats.story_pages, note: 'source file format repaired; all pages preserved verbatim' });
say('');

/* -------- PART 8: retire the two duplicate a-calm-tale episode rows -------- */
say('-- PART 8: a-calm-tale is a story series. Its planned slate in 05-qisas/README.md is four');
say('--   STORIES, and all four now exist with real page text. The two `episodes` rows duplicated');
say('--   story-01-bird-home and story-02-goodnight-toys as video episodes, had no script of their');
say('--   own, and were the only two production episodes without one. Archive rather than delete.');
for (const id of ['episode-preschool-calm-01-bird-home', 'episode-preschool-calm-02-goodnight-toys']) {
  say(`UPDATE episodes SET status='archived', is_published=0, published_at=NULL, updated_at=datetime('now') WHERE id=${q(id)};`);
  stats.archived_eps += 1;
  audit('archive', 'episode', id, { reason: 'duplicates a qisas story that now carries the real page text; qisas delivers stories, not video episodes' });
}
say('');

fs.writeFileSync(process.argv[2], out.join('\n') + '\n', 'utf8');
console.log(`SQL written: ${process.argv[2]}   statements: ${out.filter((l) => l.trim() && !l.startsWith('--')).length}`);
for (const [k, v] of Object.entries(stats)) console.log(`  ${k.padEnd(16)}${v}`);
console.log('');
console.log('engine remap applied:');
for (const r of games.engine_remap ?? []) console.log(`  ${r.game_id.padEnd(38)} ${String(r.from).padEnd(18)} -> ${r.to}`);
