// Generates the SQL that loads the authored slate into D1.
//
// Sources, all real:
//   - docs/content/planets/*/_manifest-*.json   (the 10 newly authored series)
//   - _content.json                              (the 10 pre-existing qisas story scripts)
//   - _islamic.json                              (the Islamic planet's declared STRUCTURE)
//   - docs/games/engines/*.md                    (the 12 documented engine contracts)
//
// Everything lands as draft. Nothing is published. No media is claimed to exist.
import fs from 'node:fs';
import path from 'node:path';

const PLANETS_DIR = 'F:\\Projects\\cartoonapp\\docs\\content\\planets';
const rd = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''));

const manifests = rd('_manifests.json').manifests;
const scripts = rd('_content.json');
const islamic = rd('_islamic.json');

const q = (v) => (v === null || v === undefined || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined || Number.isNaN(Number(v)) ? 'NULL' : String(Number(v)));
const j = (v) => q(JSON.stringify(v ?? []));
const jo = (v) => q(JSON.stringify(v ?? {}));

const out = [];
const say = (s) => out.push(s);
let seq = 0;
const audit = (action, type, id, details) => {
  seq += 1;
  say(`INSERT INTO audit_logs (id, actor_id, action, entity_type, entity_id, details) VALUES (${q(`audit-slate-${String(seq).padStart(4, '0')}`)}, 'content-slate-authoring', ${q(action)}, ${q(type)}, ${q(id)}, ${q(JSON.stringify(details))});`);
};
const tracksForRange = (min, max) => ['preschool', 'kids', 'junior'].filter((t) => {
  const b = t === 'preschool' ? [3, 5] : t === 'kids' ? [6, 8] : [9, 12];
  return min <= b[1] && max >= b[0];
});
const objId = (code) => `objective-${code.replace(/\./g, '-')}`;
const SKILLS = new Set(['coding', 'memory', 'observation', 'reading', 'writing', 'addition', 'counting', 'honesty']);

const stats = {
  engines: 0, series: 0, seasons: 0, objectives: 0, episodes: 0, stories: 0, story_pages: 0,
  books: 0, games: 0, projects: 0, characters: 0, reviews: 0, islamic_series: 0,
};

say('-- Majarra content slate load. Generated by scripts/_audit_load_slate.mjs');
say('-- Everything is created as draft. No content is published. No media is claimed to exist.');
say('');

/* ---------------- PART 1: the 12 documented game engines ---------------- */
say('-- PART 1: register the 12 engine contracts from docs/games/engines/.');
say('--         D1 held only 5 placeholder engines whose ids matched no documented contract.');
const ENGINES = [
  ['match_pairs', 'مطابقة كبيرة', 'مطابقة صورة بصورة أو صورة بصوت، بأهداف لمس كبيرة.', ['tap', 'drag_match'], 'preschool,kids'],
  ['trace_color', 'تتبّع وتلوين', 'تتبّع مسار أو تلوين منطقة داخل حدود.', ['trace', 'fill'], 'preschool'],
  ['sort_bins', 'تصنيف', 'توزيع عناصر على صناديق بصفة واحدة معلنة.', ['drag_to_bin', 'tap_bin'], 'preschool,kids,junior'],
  ['memory_flip', 'ذاكرة', 'قلب بطاقات لإيجاد أزواج. ترفيه أولًا.', ['flip_pairs'], 'preschool,kids'],
  ['count_quantity', 'عدّ وكميات', 'عدّ عناصر وربط العدد بالكمية ثم بالرمز.', ['count', 'select_numeral'], 'preschool,kids'],
  ['sequence_order', 'ترتيب تسلسل', 'ترتيب خطوات أو أحداث في تسلسل صحيح.', ['drag_order', 'tap_order'], 'kids,junior'],
  ['word_build', 'بناء الكلمة', 'تركيب كلمة من مقاطع أو حروف.', ['drag_letter', 'drag_syllable'], 'kids'],
  ['rhythm_tap', 'إيقاع ونغمة', 'لمس على إيقاع. ترفيه أولًا.', ['tap_beat'], 'preschool,kids,junior'],
  ['logic_pattern', 'منطق وأنماط', 'إكمال نمط أو استنتاج قاعدته.', ['complete_pattern', 'infer_rule'], 'kids,junior'],
  ['block_code', 'برمجة بالبلوكات', 'تركيب أوامر في بلوكات وتشغيلها ثم تصحيحها.', ['assemble_blocks', 'run', 'debug'], 'junior'],
  ['sim_lab', 'مختبر محاكاة', 'تغيير متغيّر واحد وملاحظة الأثر.', ['set_variable', 'run_trial', 'compare'], 'junior'],
  ['timeline_map', 'خط زمني وخريطة', 'ترتيب على خط زمن أو تحديد موقع على خريطة.', ['place_on_timeline', 'place_on_map'], 'junior'],
];
for (const [id, nameAr, desc, mech, tracks] of ENGINES) {
  say(`INSERT OR IGNORE INTO game_engines (id, name_ar, description, mechanics) VALUES (${q(id)}, ${q(nameAr)}, ${q(desc)}, ${jo({ mechanics: mech, declared_tracks: tracks.split(','), contract: `docs/games/engines/${id}.md` })});`);
  stats.engines += 1;
}
audit('bulk_create', 'game_engine', null, { count: ENGINES.length, source: 'docs/games/engines/*.md' });
say('');

/* ---------------- PART 2: the 10 authored series ---------------- */
say('-- PART 2: the newly authored series, one block per manifest.');
for (const m of manifests) {
  const s = m.series;
  const sid = `series-${s.slug}`;
  const seasonId = `season-${s.slug}-01`;
  say('');
  say(`-- ${'='.repeat(72)}`);
  say(`-- ${s.slug}  (planet ${m.planet_id}, ${s.track} ${s.age_min}-${s.age_max}, ${s.type})`);
  say(`-- purpose: ${String(s.purpose ?? '').replace(/\s+/g, ' ').slice(0, 300)}`);
  say(`-- ${'='.repeat(72)}`);

  say(`INSERT OR IGNORE INTO series (id, title_ar, title_en, slug, planet_id, type, age_min, age_max, reading_level, interaction_mode, supervision_level, description_ar, learning_goals, languages, difficulty, production_level, status, is_free, price_tier, safety_notes, sort_order) VALUES (${q(sid)}, ${q(s.title_ar)}, ${q(s.title_en)}, ${q(s.slug)}, ${q(m.planet_id)}, ${q(s.type)}, ${n(s.age_min)}, ${n(s.age_max)}, ${q(s.reading_level)}, ${q(s.interaction_mode)}, ${q(s.supervision_level)}, ${q(s.description_ar)}, ${j(s.learning_goals)}, ${j(s.languages ?? ['ar'])}, ${q(s.difficulty)}, ${q(s.production_level)}, 'draft', ${s.is_free ? 1 : 0}, ${q(s.price_tier)}, ${q(s.safety_notes)}, 100);`);
  say(`INSERT OR IGNORE INTO series_tracks (series_id, track_id) VALUES (${q(sid)}, ${q(s.track)});`);
  say(`INSERT OR IGNORE INTO series_categories (series_id, category_id, is_primary) VALUES (${q(sid)}, ${q(m.category_id)}, 1);`);
  stats.series += 1;

  const items = (m.episodes ?? []).length + (m.stories ?? []).length;
  const se = m.season ?? { season_number: 1, title_ar: 'الموسم الأول', watch_order: 'sequential' };
  say(`INSERT OR IGNORE INTO seasons (id, series_id, season_number, title_ar, episode_count, watch_order, status) VALUES (${q(seasonId)}, ${q(sid)}, ${n(se.season_number)}, ${q(se.title_ar)}, ${items}, ${q(se.watch_order)}, 'draft');`);
  stats.seasons += 1;

  for (const o of m.objectives ?? []) {
    const oid = objId(o.code);
    const skill = SKILLS.has(o.skill) ? o.skill : null;
    say(`INSERT OR IGNORE INTO learning_objectives (id, code, title_ar, description_ar, skill_id, age_min, age_max, measurable_criteria) VALUES (${q(oid)}, ${q(o.code)}, ${q(o.title_ar)}, ${q(o.criteria_ar)}, ${q(skill)}, ${n(o.age_min)}, ${n(o.age_max)}, ${q(o.criteria_ar)});`);
    for (const t of tracksForRange(o.age_min, o.age_max)) {
      say(`INSERT OR IGNORE INTO learning_objective_tracks (objective_id, track_id) VALUES (${q(oid)}, ${q(t)});`);
    }
    stats.objectives += 1;
  }

  const epId = (e) => `episode-${s.slug}-${String(e.episode_number).padStart(2, '0')}-${e.slug ?? String(e.episode_number)}`;
  for (const e of m.episodes ?? []) {
    const id = epId(e);
    say(`INSERT OR IGNORE INTO episodes (id, series_id, season_id, episode_number, title_ar, description_ar, duration_seconds, age_min, age_max, reading_level, interaction_mode, supervision_level, safety_notes, learning_objective_id, new_words, skills, prerequisites, mastery_criteria, parent_guide_ar, questions, family_activity_ar, difficulty, status, is_free, is_published) VALUES (${q(id)}, ${q(sid)}, ${q(seasonId)}, ${n(e.episode_number)}, ${q(e.title_ar)}, ${q(e.description_ar)}, ${n(e.duration_seconds)}, ${n(e.age_min)}, ${n(e.age_max)}, ${q(e.reading_level)}, ${q(e.interaction_mode)}, ${q(e.supervision_level)}, ${q(e.safety_notes)}, ${q(objId(e.objective_code))}, ${j(e.new_words)}, ${j(e.skills)}, ${j(e.prerequisites)}, ${q(e.mastery_criteria)}, ${q(e.parent_guide_ar)}, ${j(e.questions)}, ${q(e.family_activity_ar)}, ${q(e.difficulty)}, 'draft', ${e.is_free ? 1 : 0}, 0);`);
    for (const t of tracksForRange(e.age_min, e.age_max)) {
      say(`INSERT OR IGNORE INTO episode_tracks (episode_id, track_id) VALUES (${q(id)}, ${q(t)});`);
    }
    stats.episodes += 1;
  }

  for (const st of m.stories ?? []) {
    const stId = `story-${st.slug}`;
    say(`INSERT OR IGNORE INTO stories (id, series_id, season_id, slug, title_ar, title_en, description_ar, type, age_min, age_max, reading_level, interaction_mode, supervision_level, default_language, languages, status, is_free, price_tier, sort_order) VALUES (${q(stId)}, ${q(sid)}, ${q(seasonId)}, ${q(st.slug)}, ${q(st.title_ar)}, ${q(st.title_en)}, ${q(st.description_ar ?? st.synopsis_ar)}, ${q(st.type)}, ${n(st.age_min)}, ${n(st.age_max)}, ${q(st.reading_level)}, ${q(st.interaction_mode)}, ${q(st.supervision_level)}, ${q(st.default_language ?? 'ar')}, ${j(st.languages ?? ['ar'])}, 'draft', ${st.is_free ? 1 : 0}, ${q(st.price_tier ?? 'family')}, ${n(st.story_number ?? 0)});`);
    stats.stories += 1;
    for (const pg of st.pages ?? []) {
      const pid = `page-${st.slug}-${String(pg.page_number).padStart(3, '0')}`;
      say(`INSERT OR IGNORE INTO story_pages (id, story_id, page_number, layout, duration_ms, transition, sort_order) VALUES (${q(pid)}, ${q(stId)}, ${n(pg.page_number)}, ${q(pg.layout ?? 'full_bleed')}, ${n(pg.duration_ms || null)}, ${q(pg.motion ?? 'fade')}, ${n(pg.page_number)});`);
      say(`INSERT OR IGNORE INTO story_page_localizations (page_id, language, body_text, alt_text) VALUES (${q(pid)}, 'ar', ${q(pg.text_ar)}, ${q(pg.illustration_brief)});`);
      stats.story_pages += 1;
    }
  }

  for (const b of m.books ?? []) {
    const bid = `book-${b.slug}`;
    say(`INSERT OR IGNORE INTO books (id, series_id, title_ar, type, pages, age_min, age_max, reading_level, interaction_mode, supervision_level, safety_notes, is_free, status) VALUES (${q(bid)}, ${q(sid)}, ${q(b.title_ar)}, ${q(b.type)}, ${j(b.pages)}, ${n(b.age_min)}, ${n(b.age_max)}, ${q(b.reading_level)}, ${q(b.interaction_mode ?? s.interaction_mode)}, ${q(b.supervision_level ?? s.supervision_level)}, ${q(b.safety_notes)}, ${b.is_free ? 1 : 0}, 'draft');`);
    stats.books += 1;
  }

  for (const g of m.games ?? []) {
    const gid = `game-${g.pack_id}`;
    const linked = g.linked_episode
      ? (m.episodes ?? []).find((e) => e.episode_number === g.linked_episode)
      : null;
    say(`INSERT OR IGNORE INTO games (id, engine_id, series_id, episode_id, title_ar, learning_objective_id, age_min, age_max, reading_level, interaction_mode, supervision_level, safety_notes, difficulty, content_pack, instructions_ar, max_attempts, help_system, is_free, status) VALUES (${q(gid)}, ${q(g.engine)}, ${q(sid)}, ${linked ? q(epId(linked)) : 'NULL'}, ${q(g.title_ar)}, ${q(objId(g.objective_code))}, ${n(g.age_min)}, ${n(g.age_max)}, ${q(g.reading_level ?? s.reading_level)}, ${q(g.interaction_mode ?? s.interaction_mode)}, ${q(g.supervision_level ?? s.supervision_level)}, ${q(g.safety_notes)}, ${q(g.difficulty ?? s.difficulty)}, ${jo({ pack_id: g.pack_id, engine: g.engine, core_mechanic: g.core_mechanic, gameplay_loop: g.gameplay_loop, levels: g.levels, difficulty_progression: g.difficulty_progression, success_rule: g.success_rule, failure_rule: g.failure_rule, scoring: g.scoring, educational_feedback: g.educational_feedback, spec: g.content_pack ?? {}, implementation_status: 'design only - not implemented' })}, ${q(g.instructions_ar)}, ${n(g.max_attempts || null)}, ${jo(g.help_system ?? { model: 'graduated hints, no penalty' })}, 0, 'draft');`);
    stats.games += 1;
  }

  for (const pr of m.projects ?? []) {
    const prid = `project-${pr.slug}`;
    say(`INSERT OR IGNORE INTO projects (id, title_ar, description_ar, age_min, age_max, supervision_level, safety_notes, materials, steps, learning_objective_ids, is_free, status) VALUES (${q(prid)}, ${q(pr.title_ar)}, ${q([pr.description_ar, pr.preparation && `التحضير: ${pr.preparation}`, pr.expected_result && `النتيجة المتوقّعة: ${pr.expected_result}`, pr.explanation_ar && `التفسير: ${pr.explanation_ar}`, pr.parent_involvement && `دور ولي الأمر: ${pr.parent_involvement}`].filter(Boolean).join('\n\n'))}, ${n(pr.age_min)}, ${n(pr.age_max)}, ${q(pr.supervision_level)}, ${q(pr.safety_notes)}, ${j(pr.materials)}, ${j(pr.steps)}, ${j(pr.objective_code ? [objId(pr.objective_code)] : [])}, 0, 'draft');`);
    stats.projects += 1;
  }

  let ci = 0;
  for (const c of m.characters ?? []) {
    ci += 1;
    const cid = `character-${s.slug}-${ci}`;
    say(`INSERT OR IGNORE INTO characters (id, series_id, name_ar, role, age, description_ar, traits, speech_style, reference_images, expressions, outfits, languages, status) VALUES (${q(cid)}, ${q(sid)}, ${q(c.name_ar)}, ${q(c.role)}, ${n(c.age || null)}, ${q([c.description_ar, c.behavioural_rules?.length && `قواعد سلوكية: ${c.behavioural_rules.join(' · ')}`, c.relationships && `العلاقات: ${c.relationships}`, c.educational_role && `الدور التعليمي: ${c.educational_role}`, `الموجز البصري: ${c.visual_brief}`, 'حالة الأصول: لا توجد رسوم ولا تسجيل صوتي — الإنتاج مطلوب.'].filter(Boolean).join('\n\n'))}, ${j(c.traits)}, ${q(c.speech_style)}, '[]', '{}', '[]', ${j(['ar'])}, 'active');`);
    stats.characters += 1;
  }

  // every newly authored series needs an educational and a language review before it can advance
  for (const role of ['edu', 'lang']) {
    say(`INSERT OR IGNORE INTO content_reviews (id, entity_type, entity_id, reviewer_role, reviewer_id, status, comments) VALUES (${q(`review-${role}-${sid}`)}, 'series', ${q(sid)}, ${q(role)}, NULL, 'pending', ${q(role === 'edu' ? 'محتوى تحريري جديد — يلزم اعتماد تربوي قبل الجاهزية.' : 'محتوى تحريري جديد — يلزم اعتماد لغوي قبل الجاهزية.')});`);
    stats.reviews += 1;
  }
  audit('create', 'series', sid, { slug: s.slug, planet: m.planet_id, track: s.track, episodes: (m.episodes ?? []).length, stories: (m.stories ?? []).length, origin: 'slate authoring pass' });
}
say('');

/* ---------------- PART 3: the 10 pre-existing qisas story scripts ---------------- */
say('-- PART 3: the qisas story scripts that already existed on disk but were never entered.');
say('--         The 8 legacy `stories` rows are a pre-plan set whose slugs match the artwork');
say('--         filenames, not these scripts. They are archived, not deleted, and their cover');
say('--         artwork is reported as unmapped for an art-director decision.');
const QISAS_SERIES = { 'a-calm-tale': 'series-preschool-calm-tale', 'bedtime-stories': 'series-kids-bedtime' };
for (const st of scripts.stories) {
  const sid = QISAS_SERIES[st.series_slug];
  if (!sid) { say(`-- SKIPPED ${st.file}: no D1 series for ${st.series_slug}`); continue; }
  const slug = path.basename(st.file).replace(/^story-\d+-/, '').replace(/\.md$/, '');
  const stId = `story-${slug}`;
  const ages = st.age_min && st.age_max ? [st.age_min, st.age_max] : (st.series_slug === 'a-calm-tale' ? [3, 5] : [6, 8]);
  say(`INSERT OR IGNORE INTO stories (id, series_id, slug, title_ar, description_ar, type, age_min, age_max, reading_level, interaction_mode, supervision_level, default_language, languages, status, is_free, price_tier, sort_order) VALUES (${q(stId)}, ${q(sid)}, ${q(slug)}, ${q(st.title_ar)}, ${q(st.description_ar)}, 'picture_book', ${n(ages[0])}, ${n(ages[1])}, ${q(st.reading_level === 'pre_reader' ? 'pre_reader' : 'emerging')}, 'guided', 'recommended', 'ar', ${j(['ar'])}, 'draft', ${st.is_free ? 1 : 0}, 'family', ${n(st.story_number ?? 0)});`);
  stats.stories += 1;
  if (!st.pages?.length) { say(`-- NOTE ${st.file} declares ${st.page_count_declared} pages but its page table is in a non-standard format and yielded none. Source format fix required.`); }
  for (const pg of st.pages ?? []) {
    const pid = `page-${slug}-${String(pg.page_number).padStart(3, '0')}`;
    const motion = /static/.test(pg.motion) ? 'static' : (/pan/.test(pg.motion) ? 'pan_slow' : 'kenburns_slow');
    say(`INSERT OR IGNORE INTO story_pages (id, story_id, page_number, layout, transition, sort_order) VALUES (${q(pid)}, ${q(stId)}, ${n(pg.page_number)}, 'full_bleed', ${q(motion)}, ${n(pg.page_number)});`);
    say(`INSERT OR IGNORE INTO story_page_localizations (page_id, language, body_text, alt_text) VALUES (${q(pid)}, 'ar', ${q(pg.text)}, ${q(pg.role ? `الوظيفة السردية: ${pg.role}` : null)});`);
    stats.story_pages += 1;
  }
}
say('');
say('-- Archive the 8 pre-plan story shells superseded by the planned qisas slate.');
say("UPDATE stories SET status='archived', updated_at=datetime('now') WHERE id IN (SELECT id FROM stories WHERE slug IN ('little-moon','garden-keeper','turtle-home','star-over-palm','bird-finds-nest','paper-boat','patient-cloud','library-key'));");
audit('archive', 'story', null, { count: 8, reason: 'superseded by the planned qisas slate in docs/content/planets/05-qisas/README.md; cover artwork left unmapped for an art-director decision' });
say('');

/* ---------------- PART 4: the Islamic planet structure ---------------- */
say('-- PART 4: Islamic planet. STRUCTURE ONLY.');
say('--         series-shells.md declares 12 series and states plainly that it is structure, not');
say('--         content: every unit title in the source is <pending_sharia_review>, and it records');
say('--         that even choosing which surah appears is a religious decision. So no unit text is');
say('--         authored here. The 4 unregistered series are created because the same document');
say('--         recommends it: registering structure needs no religious approval, and leaving them');
say('--         out makes the plan itself invisible in reporting.');
const AGES = { preschool: [3, 5], kids: [6, 8], junior: [9, 12] };
const READ = { preschool: 'pre_reader', kids: 'emerging', junior: 'independent' };
const INTER = { preschool: 'tap', kids: 'guided', junior: 'independent' };
for (const s of islamic.filter((x) => x.in_db === 'no')) {
  const sid = `series-${s.slug}`;
  const [amin, amax] = AGES[s.track];
  say('');
  say(`-- ${s.slug} — declared in series-shells.md, ${s.units} units, never registered.`);
  say(`INSERT OR IGNORE INTO series (id, title_ar, slug, planet_id, type, age_min, age_max, reading_level, interaction_mode, supervision_level, description_ar, learning_goals, languages, difficulty, production_level, status, is_free, price_tier, safety_notes, sort_order) VALUES (${q(sid)}, ${q(s.title_ar)}, ${q(s.slug)}, 'islamic', ${q(s.type)}, ${n(amin)}, ${n(amax)}, ${q(READ[s.track])}, ${q(INTER[s.track])}, 'recommended', ${q(`هيكل سلسلة مخطَّطة من ${s.units} وحدة. لا يوجد نصّ. العناوين والمحتوى موقوفة على المراجعة الشرعية — RELIGIOUS SOURCE/REVIEW REQUIRED.`)}, '[]', ${j(['ar'])}, 'easy', 'motion_story', 'draft', 0, 'family', ${q('محتوى ديني — لا يُنشَر قبل اعتماد مراجع شرعي مسجَّل. المصدر والمرجع إلزاميان عند النشر وفارغان الآن.')}, 200);`);
  say(`INSERT OR IGNORE INTO series_tracks (series_id, track_id) VALUES (${q(sid)}, ${q(s.track)});`);
  say(`INSERT OR IGNORE INTO series_categories (series_id, category_id, is_primary) VALUES (${q(sid)}, 'category-faith', 1);`);
  say(`INSERT OR IGNORE INTO seasons (id, series_id, season_number, title_ar, episode_count, watch_order, status) VALUES (${q(`season-${s.slug}-01`)}, ${q(sid)}, 1, 'الموسم الأول', ${n(s.units)}, 'sequential', 'draft');`);
  say(`INSERT OR IGNORE INTO content_reviews (id, entity_type, entity_id, reviewer_role, reviewer_id, status, comments) VALUES (${q(`review-sharia-${sid}`)}, 'series', ${q(sid)}, 'sharia', NULL, 'pending', ${q('يلزم مصدر موثق واعتماد شرعي قبل كتابة أي وحدة أو الجاهزية أو النشر. اختيار السور والأذكار نفسه قرار شرعي.')});`);
  stats.islamic_series += 1; stats.seasons += 1; stats.reviews += 1;
  audit('create', 'series', sid, { planet: 'islamic', units_planned: s.units, state: 'structure only, blocked pending sharia review' });
}
say('');
say('-- Islamic Decision 1 from README.md: split the merged preschool series into its three');
say('--   planned parts. The document recommends this and notes the cost is a row edit now and a');
say('--   child-progress migration later. There are zero units, so it is safe to do now.');
const SPLIT = [
  ['preschool-adhkar-first', 'أذكاري الأولى', 6, 'بطاقة صوتية — audio_card. بلا قياس.'],
  ['preschool-manners-beautiful', 'آدابي الجميلة', 4, 'وحدة قصصية — story_unit. سؤال واحد.'],
  ['preschool-prepare-for-prayer', 'أتهيأ لصلاتي', 2, 'وحدة بصرية — illustrated_unit. بلا قياس.'],
];
for (const [slug, titleAr, units, note] of SPLIT) {
  const sid = `series-${slug}`;
  say(`INSERT OR IGNORE INTO series (id, title_ar, slug, planet_id, type, age_min, age_max, reading_level, interaction_mode, supervision_level, description_ar, learning_goals, languages, difficulty, production_level, status, is_free, price_tier, safety_notes, sort_order) VALUES (${q(sid)}, ${q(titleAr)}, ${q(slug)}, 'islamic', 'anthology', 3, 5, 'pre_reader', 'tap', 'recommended', ${q(`${note} ${units} وحدة مخطَّطة. لا يوجد نصّ — RELIGIOUS SOURCE/REVIEW REQUIRED.`)}, '[]', ${j(['ar'])}, 'easy', 'motion_story', 'draft', 0, 'family', ${q('محتوى ديني — لا يُنشَر قبل اعتماد مراجع شرعي مسجَّل.')}, 201);`);
  say(`INSERT OR IGNORE INTO series_tracks (series_id, track_id) VALUES (${q(sid)}, 'preschool');`);
  say(`INSERT OR IGNORE INTO series_categories (series_id, category_id, is_primary) VALUES (${q(sid)}, 'category-faith', 1);`);
  say(`INSERT OR IGNORE INTO seasons (id, series_id, season_number, title_ar, episode_count, watch_order, status) VALUES (${q(`season-${slug}-01`)}, ${q(sid)}, 1, 'الموسم الأول', ${units}, 'sequential', 'draft');`);
  say(`INSERT OR IGNORE INTO content_reviews (id, entity_type, entity_id, reviewer_role, reviewer_id, status, comments) VALUES (${q(`review-sharia-${sid}`)}, 'series', ${q(sid)}, 'sharia', NULL, 'pending', ${q('يلزم مصدر موثق واعتماد شرعي قبل كتابة أي وحدة أو النشر.')});`);
  stats.islamic_series += 1; stats.seasons += 1; stats.reviews += 1;
  audit('create', 'series', sid, { planet: 'islamic', units_planned: units, origin: 'split of preschool-adhkar-manners-prayer per the documented recommendation' });
}
say(`UPDATE series SET status='archived', description_ar=${q('سلسلة مدمجة — فُكَّت إلى: أذكاري الأولى، آدابي الجميلة، أتهيأ لصلاتي. تنفيذًا للقرار 1 في 09-islamic/README.md.')}, updated_at=datetime('now') WHERE slug='preschool-adhkar-manners-prayer';`);
audit('archive', 'series', 'series-faith-preschool-manners', { reason: 'split into three series per Islamic Decision 1' });
say('');

/* ---------------- PART 5: hygiene ---------------- */
say('-- PART 5: keep seasons.episode_count truthful for seasons that now have real items.');
say("UPDATE seasons SET episode_count=(SELECT count(*) FROM episodes e WHERE e.season_id=seasons.id) WHERE EXISTS (SELECT 1 FROM episodes e WHERE e.season_id=seasons.id);");
say('');

fs.writeFileSync(process.argv[2], out.join('\n') + '\n', 'utf8');
console.log(`SQL written: ${process.argv[2]}`);
console.log(`statements: ${out.filter((l) => l.trim() && !l.startsWith('--')).length}`);
console.log('');
for (const [k, v] of Object.entries(stats)) console.log(`  ${k.padEnd(16)}${v}`);
