// Audit apply-step generator: emits SQL for the catalogue completion pass.
// Every value written here comes from a declared field in docs/content/planets/** or from
// an existing D1 row. Nothing is invented.
import fs from 'node:fs';

const rd = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''))[0].results;
const content = JSON.parse(fs.readFileSync('_content.json', 'utf8'));
const series = rd('_ser_map.json');
const epRows = rd('_ep_ids.json');
const seasons = rd('_seasons.json');
const skills = new Set(['coding', 'memory', 'observation', 'reading', 'writing', 'addition', 'counting', 'honesty']);

const bySlug = new Map(series.map((s) => [s.slug, s]));
const seasonBySlug = new Map(seasons.map((s) => [s.series_slug, s]));
const existing = new Map(epRows.map((e) => [`${e.series_slug}#${e.episode_number}`, e]));

// episode-id prefix already in use for each series (keeps the readable ID convention)
const prefix = new Map();
for (const e of epRows) {
  const p = e.id.replace(/^episode-/, '').replace(/-\d\d-.*$/, '');
  if (/^[0-9a-f]{8}-/.test(e.id)) continue; // API-generated UUID, not a convention
  if (!prefix.has(e.series_slug)) prefix.set(e.series_slug, p);
}

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined || Number.isNaN(v) ? 'NULL' : String(v));
const j = (v) => (v === null || v === undefined ? "'[]'" : q(JSON.stringify(v)));

// D1 CHECK constraints. The scripts use a wider vocabulary than the schema allows.
const READING = new Set(['pre_reader', 'emerging', 'independent']);
const INTERACTION = new Set(['tap', 'guided', 'mixed', 'independent']);
const SUPERVISION = new Set(['none', 'recommended', 'required']);
const READING_MAP = { fluent: 'independent' };      // matches how existing D1 rows were coerced
const INTERACTION_MAP = { interactive: 'independent', passive: 'independent' };
// 'optional' is not a schema value. Mapped UP to 'recommended', never down to 'none':
// for children's content an unclear supervision level must never be under-stated.
const SUPERVISION_MAP = { optional: 'recommended' };
const coercions = [];
function coerce(kind, value, allowed, map, where) {
  if (value === null) return null;
  if (allowed.has(value)) return value;
  const mapped = map[value];
  if (!mapped) throw new Error(`unmappable ${kind}=${value} at ${where}`);
  coercions.push({ where, kind, from: value, to: mapped });
  return mapped;
}

function tracksForRange(min, max) {
  return ['preschool', 'kids', 'junior'].filter((t) => {
    const b = t === 'preschool' ? [3, 5] : t === 'kids' ? [6, 8] : [9, 12];
    return min <= b[1] && max >= b[0];
  });
}

function skillFor(code) {
  if (code.startsWith('math.count.')) return 'counting';
  if (code.startsWith('math.add')) return 'addition';
  if (code.startsWith('skill.ct.')) return 'coding';
  if (code.startsWith('world.observe.')) return 'observation';
  if (code === 'lang.letters.trace_form') return 'writing';
  return null; // no confident mapping -> leave NULL rather than guess
}

const out = [];
const say = (s) => out.push(s);
const stamp = new Date().toISOString();
let auditSeq = 0;
const audit = (action, type, id, details) => {
  auditSeq += 1;
  say(`INSERT INTO audit_logs (id, actor_id, action, entity_type, entity_id, details) VALUES (${q(`audit-catalogue-audit-${stamp.slice(0, 10)}-${String(auditSeq).padStart(4, '0')}`)}, 'catalogue-audit', ${q(action)}, ${q(type)}, ${q(id)}, ${q(JSON.stringify(details))});`);
};

say('-- Majarra catalogue completion pass. Generated by scripts/_audit_gen_sql.mjs');
say('-- Sources: docs/content/planets/** declared metadata cards + existing D1 rows.');
say('');

/* ---------- PART 1: defect fixes ---------- */
say('-- PART 1: confirmed defect fixes');
say("-- 1.1 episode-numbers-01-counting-stars is published but has no asset_links role='stream'.");
say('--      A published episode with no playable video is invalid content. Return it to draft.');
say("UPDATE episodes SET status='draft', is_published=0, published_at=NULL, updated_at=datetime('now') WHERE id='episode-numbers-01-counting-stars';");
audit('unpublish_invalid', 'episode', 'episode-numbers-01-counting-stars', { reason: 'published with no stream asset link' });
say('');
say('-- 1.2 series-kids-numbers is published but none of its episodes has a stream asset.');
say("UPDATE series SET status='draft', published_at=NULL, updated_at=datetime('now') WHERE id='series-kids-numbers';");
audit('unpublish_invalid', 'series', 'series-kids-numbers', { reason: 'published with zero playable episodes' });
say('');
say('-- 1.3 Remove the two B1-spike scaffold assets. The real poster/still assets now exist as');
say('--     public/ready rows, so these only create duplicate poster/thumbnail links.');
for (const id of ['4911bb1d-9470-4b34-8513-8a1349b7c546', '2af2423f-8d74-4e8a-8558-1547d2aef495']) {
  say(`DELETE FROM asset_links WHERE asset_id=${q(id)};`);
  say(`DELETE FROM content_assets WHERE id=${q(id)};`);
  audit('delete_duplicate', 'content_asset', id, { reason: 'B1 spike scaffold superseded by the imported asset' });
}
say('');
say('-- 1.4 mazen-wa-thaaloub has no series_categories row (planet abjad -> category-language).');
const mazen = bySlug.get('mazen-wa-thaaloub');
say(`INSERT OR IGNORE INTO series_categories (series_id, category_id, is_primary) VALUES (${q(mazen.id)}, 'category-language', 1);`);
audit('link_category', 'series', mazen.id, { category_id: 'category-language' });
say('');
say('-- 1.5 mazen-wa-thaaloub has no season while all 22 other series do. Create season 1 and');
say('--     attach its 14 real episodes.');
const mazenEps = epRows.filter((e) => e.series_slug === 'mazen-wa-thaaloub');
say(`INSERT OR IGNORE INTO seasons (id, series_id, season_number, title_ar, episode_count, watch_order, status) VALUES ('season-mazen-wa-thaaloub-01', ${q(mazen.id)}, 1, 'Ø§Ù„Ù…ÙˆØ³Ù… Ø§Ù„Ø£ÙˆÙ„', ${mazenEps.length}, 'sequential', 'published');`);
for (const e of mazenEps) say(`UPDATE episodes SET season_id='season-mazen-wa-thaaloub-01', updated_at=datetime('now') WHERE id=${q(e.id)};`);
audit('create', 'season', 'season-mazen-wa-thaaloub-01', { series_id: mazen.id, episode_count: mazenEps.length });
say('');

/* ---------- PART 2: learning objectives ---------- */
say('-- PART 2: learning_objectives (table was empty; 63 codes are declared by the scripts)');
const objectives = new Map();
for (const e of content.episodes) {
  const code = e.learning_objective_code;
  if (!code) continue;
  const cur = objectives.get(code) ?? { code, title: null, criteria: null, amin: 99, amax: 0 };
  cur.title ??= e.objective_title;
  cur.criteria ??= e.objective_criteria ?? e.mastery_criteria;
  cur.amin = Math.min(cur.amin, e.age_min);
  cur.amax = Math.max(cur.amax, e.age_max);
  objectives.set(code, cur);
}
for (const o of [...objectives.values()].sort((a, b) => a.code.localeCompare(b.code))) {
  const id = `objective-${o.code.replace(/\./g, '-')}`;
  const skill = skillFor(o.code);
  say(`INSERT OR IGNORE INTO learning_objectives (id, code, title_ar, description_ar, skill_id, age_min, age_max, measurable_criteria) VALUES (${q(id)}, ${q(o.code)}, ${q(o.title)}, ${q(o.criteria)}, ${skill && skills.has(skill) ? q(skill) : 'NULL'}, ${n(o.amin)}, ${n(o.amax)}, ${q(o.criteria)});`);
  for (const t of tracksForRange(o.amin, o.amax)) {
    say(`INSERT OR IGNORE INTO learning_objective_tracks (objective_id, track_id) VALUES (${q(id)}, ${q(t)});`);
  }
}
audit('bulk_create', 'learning_objective', null, { count: objectives.size, source: 'docs/content/planets/** episode cards' });
say('');

/* ---------- PART 3: complete existing episodes ---------- */
say('-- PART 3: fill declared-but-empty editorial fields on episodes that already exist.');
say('--         reading_level / interaction_mode / title_ar are deliberately NOT touched.');
let updated = 0;
for (const e of content.episodes) {
  const hit = existing.get(`${e.series_slug}#${e.episode_number}`);
  if (!hit) continue;
  updated += 1;
  const sets = [
    `duration_seconds=${n(e.duration_seconds)}`,
    `learning_objective_id=${q(`objective-${e.learning_objective_code.replace(/\./g, '-')}`)}`,
    `mastery_criteria=COALESCE(NULLIF(mastery_criteria,''), ${q(e.mastery_criteria)})`,
    `parent_guide_ar=COALESCE(NULLIF(parent_guide_ar,''), ${q(e.parent_guide_ar)})`,
    `family_activity_ar=COALESCE(NULLIF(family_activity_ar,''), ${q(e.family_activity_ar)})`,
    `safety_notes=COALESCE(NULLIF(safety_notes,''), ${q(e.safety_notes)})`,
    `questions=CASE WHEN questions IN ('','[]') THEN ${j(e.questions)} ELSE questions END`,
    `new_words=CASE WHEN new_words IN ('','[]') THEN ${j(e.new_words)} ELSE new_words END`,
    `description_ar=COALESCE(NULLIF(description_ar,''), ${q(e.description_ar)})`,
    "updated_at=datetime('now')",
  ];
  say(`UPDATE episodes SET ${sets.join(', ')} WHERE id=${q(hit.id)};`);
}
audit('bulk_update', 'episode', null, { count: updated, fields: 'duration_seconds, learning_objective_id, mastery_criteria, parent_guide_ar, family_activity_ar, safety_notes, questions, new_words, description_ar' });
say('');

/* ---------- PART 4: create missing episodes ---------- */
say('-- PART 4: create episodes that have a complete script on disk but no D1 row.');
say("--         All are created as status='draft', is_published=0. None becomes publishable here:");
say('--         they still have no video asset.');
const created = [];
for (const e of content.episodes) {
  if (existing.has(`${e.series_slug}#${e.episode_number}`)) continue;
  const sr = bySlug.get(e.series_slug);
  const pre = prefix.get(e.series_slug);
  if (!sr || !pre) throw new Error(`no series/prefix for ${e.series_slug}`);
  const slugPart = e.file.split('/').pop().replace(/^ep-\d+-/, '').replace(/\.md$/, '');
  const id = `episode-${pre}-${String(e.episode_number).padStart(2, '0')}-${slugPart}`;
  const season = seasonBySlug.get(e.series_slug);
  const reading = coerce('reading_level', e.reading_level, READING, READING_MAP, id);
  const interaction = coerce('interaction_mode', e.interaction_mode, INTERACTION, INTERACTION_MAP, id);
  const supervision = coerce('supervision_level', e.supervision_level, SUPERVISION, SUPERVISION_MAP, id) ?? 'recommended';
  const tracks = tracksForRange(e.age_min, e.age_max);
  created.push({ id, series: sr.id, slug: e.series_slug, num: e.episode_number, tracks });
  say(`INSERT INTO episodes (id, series_id, season_id, episode_number, title_ar, description_ar, duration_seconds, age_min, age_max, reading_level, interaction_mode, supervision_level, safety_notes, learning_objective_id, new_words, skills, prerequisites, mastery_criteria, parent_guide_ar, questions, family_activity_ar, difficulty, status, is_free, is_published) VALUES (${q(id)}, ${q(sr.id)}, ${season ? q(season.id) : 'NULL'}, ${n(e.episode_number)}, ${q(e.title_ar)}, ${q(e.description_ar)}, ${n(e.duration_seconds)}, ${n(e.age_min)}, ${n(e.age_max)}, ${q(reading)}, ${q(interaction)}, ${q(supervision)}, ${q(e.safety_notes)}, ${q(`objective-${e.learning_objective_code.replace(/\./g, '-')}`)}, ${j(e.new_words)}, '[]', ${j(e.prerequisites)}, ${q(e.mastery_criteria)}, ${q(e.parent_guide_ar)}, ${j(e.questions)}, ${q(e.family_activity_ar)}, ${q(e.difficulty)}, 'draft', ${e.is_free}, 0);`);
  for (const t of tracks) say(`INSERT OR IGNORE INTO episode_tracks (episode_id, track_id) VALUES (${q(id)}, ${q(t)});`);
}
audit('bulk_create', 'episode', null, { count: created.length, source: 'docs/content/planets/** episode scripts', status: 'draft' });
say('');

/* ---------- PART 5: season episode_count ---------- */
say('-- PART 5: seasons.episode_count was a planning figure; align it with reality.');
say("UPDATE seasons SET episode_count=(SELECT count(*) FROM episodes e WHERE e.season_id=seasons.id) WHERE EXISTS (SELECT 1 FROM episodes e WHERE e.season_id=seasons.id);");
audit('bulk_update', 'season', null, { field: 'episode_count', reason: 'aligned with actual episode rows' });
say('');

fs.writeFileSync(process.argv[2], out.join('\n') + '\n', { encoding: 'utf8' });

console.log(`SQL written: ${process.argv[2]}   statements: ${out.filter((l) => l.trim() && !l.startsWith('--')).length}`);
console.log(`learning_objectives to create: ${objectives.size}`);
console.log(`existing episodes to complete:  ${updated}`);
console.log(`episodes to create:             ${created.length}`);
console.log('');
console.log('new episode rows:');
const byS = {};
for (const c of created) (byS[c.slug] ||= []).push(c);
for (const k of Object.keys(byS).sort()) {
  console.log(`  ${k}`);
  for (const c of byS[k].sort((a, b) => a.num - b.num)) console.log(`      ${c.id}   tracks=[${c.tracks}]`);
}
console.log('');
console.log(`vocabulary coercions required by the D1 CHECK constraints: ${coercions.length}`);
const cg = {};
for (const c of coercions) cg[`${c.kind}: ${c.from} -> ${c.to}`] = (cg[`${c.kind}: ${c.from} -> ${c.to}`] || 0) + 1;
for (const [k, v] of Object.entries(cg)) console.log(`  ${k}   (${v} episodes)`);
