SELECT 'planets' AS k, count(*) AS v FROM planets;
SELECT 'sections (categories)' AS k, count(*) AS v FROM categories;
SELECT 'Majarra series (active)' AS k, count(*) AS v FROM series WHERE content_class='production' AND status<>'archived';
SELECT 'Majarra seasons' AS k, count(*) AS v FROM seasons se JOIN series s ON s.id=se.series_id WHERE s.content_class='production' AND s.status<>'archived';
SELECT 'Majarra episodes' AS k, count(*) AS v FROM episodes e JOIN series s ON s.id=e.series_id WHERE s.content_class='production' AND s.status<>'archived' AND e.status<>'archived';
SELECT 'Majarra stories' AS k, count(*) AS v FROM stories st JOIN series s ON s.id=st.series_id WHERE s.content_class='production' AND st.status<>'archived';
SELECT 'Majarra story pages' AS k, count(*) AS v FROM story_pages sp JOIN stories st ON st.id=sp.story_id JOIN series s ON s.id=st.series_id WHERE s.content_class='production' AND st.status<>'archived';
SELECT 'Majarra books' AS k, count(*) AS v FROM books;
SELECT 'Majarra book pages' AS k, count(*) AS v FROM books, json_each(books.pages);
SELECT 'Majarra games' AS k, count(*) AS v FROM games g JOIN series s ON s.id=g.series_id WHERE s.content_class='production';
SELECT 'game engines registered' AS k, count(*) AS v FROM game_engines;
SELECT 'Majarra activities' AS k, count(*) AS v FROM projects;
SELECT 'Majarra characters' AS k, count(*) AS v FROM characters c JOIN series s ON s.id=c.series_id WHERE s.content_class='production';
SELECT 'learning objectives' AS k, count(*) AS v FROM learning_objectives;
SELECT 'objective age-track rows' AS k, count(*) AS v FROM learning_objective_tracks;
SELECT 'content reviews pending' AS k, count(*) AS v FROM content_reviews WHERE status='pending';
SELECT 'TEST FIXTURE series' AS k, count(*) AS v FROM series WHERE content_class='test_fixture';
SELECT 'TEST FIXTURE episodes' AS k, count(*) AS v FROM episodes e JOIN series s ON s.id=e.series_id WHERE s.content_class='test_fixture';
SELECT 'archived (superseded) series' AS k, count(*) AS v FROM series WHERE status='archived';
SELECT 'archived stories' AS k, count(*) AS v FROM stories WHERE status='archived';
SELECT 'archived episodes' AS k, count(*) AS v FROM episodes WHERE status='archived';
